/**
 * @packageDocumentation
 * @module api.functional.auth.producer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskProducer } from "../../../../../src/api/structures/BrokerDeskActorsProducer";

export * as password from "./password/index";
export * as email from "./email/index";

/**
 * Sign in as a producer.
 *
 * Verifies the credential, gates on email verification and activation, and
 * issues a JWT pair bound to a new session record carrying the request
 * context.
 *
 * @param body Email and password credentials.
 * @returns The producer with a freshly issued JWT pair.
 *
 * @controller BrokerDeskActorsProducerAuthController.login
 * @path POST /auth/producer/login
 * @accessor api.functional.auth.producer.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  body: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    body,
  );
}
export namespace login {
  export type Body = Primitive<IBrokerDeskProducer.ILogin>;
  export type Output = Primitive<IBrokerDeskProducer.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/producer/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/producer/login";
}

/**
 * Refresh the access token of an existing producer session.
 *
 * @param body Refresh token previously issued by login.
 * @returns Renewed authorization payload bound to the same session.
 *
 * @controller BrokerDeskActorsProducerAuthController.refresh
 * @path POST /auth/producer/refresh
 * @accessor api.functional.auth.producer.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
  body: refresh.Body,
): Promise<refresh.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...refresh.METADATA,
      template: refresh.METADATA.path,
      path: refresh.path(),
    },
    body,
  );
}
export namespace refresh {
  export type Body = Primitive<IBrokerDeskProducer.IRefresh>;
  export type Output = Primitive<IBrokerDeskProducer.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/producer/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/producer/refresh";
}
