/**
 * @packageDocumentation
 * @module api.functional.organization.addresses
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskAddress } from "../../../../../src/api/structures/BrokerDeskCrmAddress";

/**
 * List office locations of the acting organization.
 *
 * @returns The organization's owned addresses.
 *
 * @controller BrokerDeskCrmOrganizationAddressController.index
 * @path GET /organization/addresses
 * @accessor api.functional.organization.addresses.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(connection: IConnection): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(),
  });
}
export namespace index {
  export type Output = Primitive<Array<IBrokerDeskAddress>>;

  export const METADATA = {
    method: "GET",
    path: "/organization/addresses",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/organization/addresses";
}

/**
 * Bind a new typed address as an office location of the acting
 * organization.
 *
 * @param body Address creation payload.
 * @returns The created address with ownership binding.
 *
 * @controller BrokerDeskCrmOrganizationAddressController.create
 * @path POST /organization/addresses
 * @accessor api.functional.organization.addresses.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskAddress.ICreate>;
  export type Output = Primitive<IBrokerDeskAddress>;

  export const METADATA = {
    method: "POST",
    path: "/organization/addresses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/organization/addresses";
}

/**
 * Read one office location of the acting organization.
 *
 * @param addressId Primary key of the address.
 * @returns The address detail.
 *
 * @controller BrokerDeskCrmOrganizationAddressController.at
 * @path GET /organization/addresses/:addressId
 * @accessor api.functional.organization.addresses.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  addressId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(addressId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskAddress>;

  export const METADATA = {
    method: "GET",
    path: "/organization/addresses/:addressId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (addressId: string & tags.Format<"uuid">) =>
    `/organization/addresses/${encodeURIComponent(addressId?.toString() ?? "null")}`;
}
