/**
 * @packageDocumentation
 * @module api.functional.auth.admin
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../src/api/structures/BrokerDeskActorsAdmin";

export * as password from "./password/index";
export * as email from "./email/index";
export * as sessions from "./sessions/index";
export * as me from "./me/index";

/**
 * Register the first administrator together with a new brokerage
 * organization.
 *
 * Public entry point of a brand-new tenant: the organization profile and
 * the founding administrator account are created atomically in one
 * transaction, and a fresh JWT pair is returned. Subsequent staff accounts
 * are provisioned by invitation instead of self-registration.
 *
 * @param body Organization profile plus founding administrator credentials.
 * @returns The created administrator with freshly issued access and refresh tokens.
 *
 * @controller BrokerDeskActorsAdminAuthController.join
 * @path POST /auth/admin/join
 * @accessor api.functional.auth.admin.join
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function join(
  connection: IConnection,
  body: join.Body,
): Promise<join.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...join.METADATA,
      template: join.METADATA.path,
      path: join.path(),
    },
    body,
  );
}
export namespace join {
  export type Body = Primitive<IBrokerDeskAdmin.IJoin>;
  export type Output = Primitive<IBrokerDeskAdmin.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/join";
}

/**
 * Sign in as a brokerage administrator.
 *
 * Verifies the credential, rejects deactivated accounts, and issues a
 * short-lived access token paired with a longer-lived refresh token bound
 * to a new session record carrying the request context.
 *
 * @param body Email and password credentials.
 * @returns The administrator with a freshly issued JWT pair.
 *
 * @controller BrokerDeskActorsAdminAuthController.login
 * @path POST /auth/admin/login
 * @accessor api.functional.auth.admin.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  body: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    body,
  );
}
export namespace login {
  export type Body = Primitive<IBrokerDeskAdmin.ILogin>;
  export type Output = Primitive<IBrokerDeskAdmin.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/login";
}

/**
 * Refresh the access token of an existing administrator session.
 *
 * Re-reads the administrator's current activation status at refresh time so
 * renewed credentials always reflect present account state.
 *
 * @param body Refresh token previously issued by join or login.
 * @returns Renewed authorization payload bound to the same session.
 *
 * @controller BrokerDeskActorsAdminAuthController.refresh
 * @path POST /auth/admin/refresh
 * @accessor api.functional.auth.admin.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
  body: refresh.Body,
): Promise<refresh.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...refresh.METADATA,
      template: refresh.METADATA.path,
      path: refresh.path(),
    },
    body,
  );
}
export namespace refresh {
  export type Body = Primitive<IBrokerDeskAdmin.IRefresh>;
  export type Output = Primitive<IBrokerDeskAdmin.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/refresh";
}
