/**
 * @packageDocumentation
 * @module api.functional.policies.cancellations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPolicyCancellation } from "../../../../../src/api/structures/BrokerDeskPolicy";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List historical cancellation records of a policy.
 *
 * A policy may accumulate several cancellations over its lifetime when
 * reinstatements occur between them.
 *
 * @param policyId Owning policy id.
 * @returns Paginated cancellation summaries.
 *
 * @controller BrokerDeskPolicySubsidiaryController.indexCancellations
 * @path GET /policies/:policyId/cancellations
 * @accessor api.functional.policies.cancellations.indexCancellations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexCancellations(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
): Promise<indexCancellations.Output> {
  return PlainFetcher.fetch(connection, {
    ...indexCancellations.METADATA,
    template: indexCancellations.METADATA.path,
    path: indexCancellations.path(policyId),
  });
}
export namespace indexCancellations {
  export type Output = Primitive<IPage<IBrokerDeskPolicyCancellation.ISummary>>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/cancellations",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/cancellations`;
}

/**
 * Retrieve a single cancellation record including its reinstatement when present.
 *
 * @param policyId Owning policy id.
 * @param cancellationId Target cancellation id.
 * @returns The cancellation record.
 *
 * @controller BrokerDeskPolicySubsidiaryController.atCancellation
 * @path GET /policies/:policyId/cancellations/:cancellationId
 * @accessor api.functional.policies.cancellations.atCancellation
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function atCancellation(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  cancellationId: string & tags.Format<"uuid">,
): Promise<atCancellation.Output> {
  return PlainFetcher.fetch(connection, {
    ...atCancellation.METADATA,
    template: atCancellation.METADATA.path,
    path: atCancellation.path(policyId, cancellationId),
  });
}
export namespace atCancellation {
  export type Output = Primitive<IBrokerDeskPolicyCancellation>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/cancellations/:cancellationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    cancellationId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/cancellations/${encodeURIComponent(cancellationId?.toString() ?? "null")}`;
}
