/**
 * @packageDocumentation
 * @module api.functional.admin.admins
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../src/api/structures/BrokerDeskActorsAdmin";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List administrator accounts of the caller's organization.
 *
 * @param body Search, filter, and pagination criteria.
 * @returns Paginated administrator summaries.
 *
 * @controller BrokerDeskActorsAdminsController.index
 * @path PATCH /admin/admins
 * @accessor api.functional.admin.admins.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskAdmin.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskAdmin.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/admins",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/admins";
}

/**
 * Invite a new administrator into the caller's organization.
 *
 * The invited account receives a verification / setup message and completes
 * its credential out of band.
 *
 * @param body Invitation body (email, display name, activation standing).
 * @returns The newly provisioned administrator.
 *
 * @controller BrokerDeskActorsAdminsController.create
 * @path POST /admin/admins
 * @accessor api.functional.admin.admins.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskAdmin.ICreate>;
  export type Output = Primitive<IBrokerDeskAdmin>;

  export const METADATA = {
    method: "POST",
    path: "/admin/admins",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/admins";
}

/**
 * Retrieve one administrator account in detail.
 *
 * @param adminId Target administrator identifier.
 * @returns The administrator record.
 *
 * @controller BrokerDeskActorsAdminsController.at
 * @path GET /admin/admins/:adminId
 * @accessor api.functional.admin.admins.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  adminId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(adminId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskAdmin>;

  export const METADATA = {
    method: "GET",
    path: "/admin/admins/:adminId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (adminId: string & tags.Format<"uuid">) =>
    `/admin/admins/${encodeURIComponent(adminId?.toString() ?? "null")}`;
}

/**
 * Update an administrator account.
 *
 * Role-sensitive changes such as deactivation terminate the colleague's
 * open sessions immediately; the last active administrator of an
 * organization is protected.
 *
 * @param adminId Target administrator identifier.
 * @param body Mutable account fields.
 * @returns The updated administrator record.
 *
 * @controller BrokerDeskActorsAdminsController.update
 * @path PUT /admin/admins/:adminId
 * @accessor api.functional.admin.admins.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  adminId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(adminId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskAdmin.IUpdate>;
  export type Output = Primitive<IBrokerDeskAdmin>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/admins/:adminId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (adminId: string & tags.Format<"uuid">) =>
    `/admin/admins/${encodeURIComponent(adminId?.toString() ?? "null")}`;
}

/**
 * Soft-delete an administrator account.
 *
 * The row is retained for audit traceability while disappearing from
 * listings; self-removal and removal of the last active administrator are
 * rejected.
 *
 * @param adminId Target administrator identifier.
 *
 * @controller BrokerDeskActorsAdminsController.erase
 * @path DELETE /admin/admins/:adminId
 * @accessor api.functional.admin.admins.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  adminId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(adminId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/admin/admins/:adminId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (adminId: string & tags.Format<"uuid">) =>
    `/admin/admins/${encodeURIComponent(adminId?.toString() ?? "null")}`;
}
