/**
 * @packageDocumentation
 * @module api.functional.clients.me.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskClientSession } from "../../../../../../src/api/structures/BrokerDeskActorsClient";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the sign-in sessions of the authenticated portal client.
 *
 * @param body Pagination criteria.
 * @returns Paginated session history of the caller.
 *
 * @controller BrokerDeskActorsClientMeController.indexSessions
 * @path PATCH /clients/me/sessions
 * @accessor api.functional.clients.me.sessions.indexSessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexSessions(
  connection: IConnection,
  body: indexSessions.Body,
): Promise<indexSessions.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...indexSessions.METADATA,
      template: indexSessions.METADATA.path,
      path: indexSessions.path(),
    },
    body,
  );
}
export namespace indexSessions {
  export type Body = Primitive<IBrokerDeskClientSession.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskClientSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/clients/me/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/clients/me/sessions";
}
