/**
 * @packageDocumentation
 * @module api.functional.auth.admin.password.reset.confirm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../../../../src/api/structures/BrokerDeskActorsAdmin";

/**
 * Consume a password reset token and set a new password.
 *
 * Expired or already-consumed tokens are rejected and leave the account
 * unchanged, requiring a fresh request.
 *
 * @param body One-time token plus the replacement password.
 *
 * @controller BrokerDeskActorsAdminAuthController.confirmPasswordReset
 * @path POST /auth/admin/password/reset/confirm
 * @accessor api.functional.auth.admin.password.reset.confirm.confirmPasswordReset
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function confirmPasswordReset(
  connection: IConnection,
  body: confirmPasswordReset.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...confirmPasswordReset.METADATA,
      template: confirmPasswordReset.METADATA.path,
      path: confirmPasswordReset.path(),
    },
    body,
  );
}
export namespace confirmPasswordReset {
  export type Body = Primitive<IBrokerDeskAdmin.IConfirmPasswordReset>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/password/reset/confirm",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/password/reset/confirm";
}
