/**
 * @packageDocumentation
 * @module api.functional.products.commission_schedule
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskCommissionSchedule } from "../../../../../src/api/structures/BrokerDeskCatalogueProduct";

/**
 * Fetch a product's default commission schedule.
 *
 * @param productId Parent product id.
 * @returns The commission schedule, or null when the product has none.
 *
 * @controller BrokerDeskCatalogueCommissionScheduleController.at
 * @path GET /products/:productId/commission-schedule
 * @accessor api.functional.products.commission_schedule.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(productId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCommissionSchedule | null>;

  export const METADATA = {
    method: "GET",
    path: "/products/:productId/commission-schedule",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/commission-schedule`;
}

/**
 * Create a product's default commission schedule.
 *
 * ADMIN-only operation; rejected when the product already carries a
 * schedule.
 *
 * @param productId Parent product id.
 * @param body Schedule creation attributes.
 * @returns The newly created commission schedule.
 *
 * @controller BrokerDeskCatalogueCommissionScheduleController.create
 * @path POST /products/:productId/commission-schedule
 * @accessor api.functional.products.commission_schedule.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(productId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCommissionSchedule.ICreate>;
  export type Output = Primitive<IBrokerDeskCommissionSchedule>;

  export const METADATA = {
    method: "POST",
    path: "/products/:productId/commission-schedule",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/commission-schedule`;
}

/**
 * Update a product's default commission schedule.
 *
 * Rates and the tier table may be revised; downstream quote lines and
 * commissions persist their seeded figures as independent snapshots.
 *
 * @param productId Parent product id.
 * @param body Fields to update.
 * @returns The updated commission schedule.
 *
 * @controller BrokerDeskCatalogueCommissionScheduleController.update
 * @path PUT /products/:productId/commission-schedule
 * @accessor api.functional.products.commission_schedule.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(productId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCommissionSchedule.IUpdate>;
  export type Output = Primitive<IBrokerDeskCommissionSchedule>;

  export const METADATA = {
    method: "PUT",
    path: "/products/:productId/commission-schedule",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/commission-schedule`;
}

/**
 * Retire a product's default commission schedule softly.
 *
 * Historical estimate and commission lineage remains fully traceable.
 *
 * @param productId Parent product id.
 *
 * @controller BrokerDeskCatalogueCommissionScheduleController.erase
 * @path DELETE /products/:productId/commission-schedule
 * @accessor api.functional.products.commission_schedule.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(productId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/products/:productId/commission-schedule",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/commission-schedule`;
}
