/**
 * @packageDocumentation
 * @module api.functional.auth.csr.email.verify
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as request from "./request/index";
export * as confirm from "./confirm/index";
