/**
 * @packageDocumentation
 * @module api.functional.admin.clients
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskClient } from "../../../../../src/api/structures/BrokerDeskActorsClient";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List portal client identities.
 *
 * Filters by name, email, status and assigned producer; supports
 * pagination and ordering. Returns lightweight summaries suitable for
 * roster tables.
 *
 * @param body Search and pagination criteria.
 * @returns Page of client identity summaries.
 *
 * @controller BrokerDeskActorsAdminClientsController.index
 * @path PATCH /admin/clients
 * @accessor api.functional.admin.clients.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskClient.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskClient.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/clients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/clients";
}

/**
 * Retrieve a single portal client identity.
 *
 * @param clientId Target client identity key.
 * @returns Full client identity record.
 *
 * @controller BrokerDeskActorsAdminClientsController.at
 * @path GET /admin/clients/:clientId
 * @accessor api.functional.admin.clients.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  clientId: string,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(clientId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "GET",
    path: "/admin/clients/:clientId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string) =>
    `/admin/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}

/**
 * Provision a new portal client identity.
 *
 * Creates the sign-in account bound to the supplied client profile; the
 * initial credential is established through the password reset flow.
 *
 * @param body Creation payload.
 * @returns The created client identity.
 *
 * @controller BrokerDeskActorsAdminClientsController.create
 * @path POST /admin/clients
 * @accessor api.functional.admin.clients.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskClient.ICreate>;
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "POST",
    path: "/admin/clients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/clients";
}

/**
 * Update a portal client identity.
 *
 * @param clientId Target client identity key.
 * @param body Patched fields.
 * @returns The updated client identity.
 *
 * @controller BrokerDeskActorsAdminClientsController.update
 * @path PUT /admin/clients/:clientId
 * @accessor api.functional.admin.clients.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  clientId: string,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(clientId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskClient.IUpdate>;
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/clients/:clientId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string) =>
    `/admin/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}

/**
 * Deactivate a portal client identity.
 *
 * Soft-deletes the identity; historical records are preserved.
 *
 * @param clientId Target client identity key.
 *
 * @controller BrokerDeskActorsAdminClientsController.erase
 * @path DELETE /admin/clients/:clientId
 * @accessor api.functional.admin.clients.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  clientId: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(clientId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/admin/clients/:clientId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string) =>
    `/admin/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}
