/**
 * @packageDocumentation
 * @module api.functional.auth.producer.password.reset.request
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskProducer } from "../../../../../../../../src/api/structures/BrokerDeskActorsProducer";

/**
 * Request a single-use password reset token by email.
 *
 * Responds identically whether or not the address is registered, to avoid
 * revealing account existence; delivery may be logged in development.
 *
 * @param body Email address targeting the reset.
 *
 * @controller BrokerDeskActorsProducerAuthController.requestPasswordReset
 * @path POST /auth/producer/password/reset/request
 * @accessor api.functional.auth.producer.password.reset.request.requestPasswordReset
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function requestPasswordReset(
  connection: IConnection,
  body: requestPasswordReset.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...requestPasswordReset.METADATA,
      template: requestPasswordReset.METADATA.path,
      path: requestPasswordReset.path(),
    },
    body,
  );
}
export namespace requestPasswordReset {
  export type Body = Primitive<IBrokerDeskProducer.IRequestPasswordReset>;

  export const METADATA = {
    method: "POST",
    path: "/auth/producer/password/reset/request",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/producer/password/reset/request";
}
