/**
 * @packageDocumentation
 * @module api.functional.auth.csr.email.verify.confirm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskCsr } from "../../../../../../../../src/api/structures/BrokerDeskActorsCsr";

/**
 * Confirm email ownership with a verification token.
 *
 * Completing an invitation setup link counts as verification: when the
 * invited CSR supplies an initial password here, the credential is
 * established and the activated account may sign in immediately.
 *
 * @param body Email address, one-time token, and optional initial password.
 *
 * @controller BrokerDeskActorsCsrAuthController.confirmEmailVerification
 * @path POST /auth/csr/email/verify/confirm
 * @accessor api.functional.auth.csr.email.verify.confirm.confirmEmailVerification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function confirmEmailVerification(
  connection: IConnection,
  body: confirmEmailVerification.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...confirmEmailVerification.METADATA,
      template: confirmEmailVerification.METADATA.path,
      path: confirmEmailVerification.path(),
    },
    body,
  );
}
export namespace confirmEmailVerification {
  export type Body = Primitive<IBrokerDeskCsr.IConfirmEmailVerification>;

  export const METADATA = {
    method: "POST",
    path: "/auth/csr/email/verify/confirm",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/csr/email/verify/confirm";
}
