/**
 * @packageDocumentation
 * @module api.functional.producers.me.licences
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskProducerLicence } from "../../../../../../src/api/structures/BrokerDeskActorsProducer";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the provincial licences qualifying the authenticated producer.
 *
 * Supports compliance-style views: filtering by expired credentials or
 * licences expiring within a number of days surfaces what needs renewal
 * before quoting or binding business in a jurisdiction.
 *
 * @param body Pagination and compliance filter criteria.
 * @returns Paginated licence history of the caller.
 *
 * @controller BrokerDeskActorsProducerMeController.indexLicences
 * @path PATCH /producers/me/licences
 * @accessor api.functional.producers.me.licences.indexLicences
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexLicences(
  connection: IConnection,
  body: indexLicences.Body,
): Promise<indexLicences.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...indexLicences.METADATA,
      template: indexLicences.METADATA.path,
      path: indexLicences.path(),
    },
    body,
  );
}
export namespace indexLicences {
  export type Body = Primitive<IBrokerDeskProducerLicence.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskProducerLicence.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/producers/me/licences",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/producers/me/licences";
}
