/**
 * @packageDocumentation
 * @module api.functional.commission_statements.mark_paid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskCommissionStatement } from "../../../../../src/api/structures/BrokerDeskBilling";

/**
 * Mark a statement paid.
 *
 * Stamps `paid_at`, transitions the statement to `paid`, and finalizes
 * the linked commissions as settled.
 *
 * @param statementId Target statement identifier.
 * @returns The settled statement.
 *
 * @controller BrokerDeskBillingCommissionStatementController.markPaid
 * @path POST /commission-statements/:statementId/mark-paid
 * @accessor api.functional.commission_statements.mark_paid.markPaid
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function markPaid(
  connection: IConnection,
  statementId: string & tags.Format<"uuid">,
): Promise<markPaid.Output> {
  return PlainFetcher.fetch(connection, {
    ...markPaid.METADATA,
    template: markPaid.METADATA.path,
    path: markPaid.path(statementId),
  });
}
export namespace markPaid {
  export type Output = Primitive<IBrokerDeskCommissionStatement>;

  export const METADATA = {
    method: "POST",
    path: "/commission-statements/:statementId/mark-paid",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (statementId: string & tags.Format<"uuid">) =>
    `/commission-statements/${encodeURIComponent(statementId?.toString() ?? "null")}/mark-paid`;
}
