/**
 * @packageDocumentation
 * @module api.functional.auth.admin.email.verify.confirm
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../../../../src/api/structures/BrokerDeskActorsAdmin";

/**
 * Confirm email ownership with a verification token.
 *
 * Consumes the token exactly once; double redemption is impossible.
 *
 * @param body Email address plus the one-time verification token.
 *
 * @controller BrokerDeskActorsAdminAuthController.confirmEmailVerification
 * @path POST /auth/admin/email/verify/confirm
 * @accessor api.functional.auth.admin.email.verify.confirm.confirmEmailVerification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function confirmEmailVerification(
  connection: IConnection,
  body: confirmEmailVerification.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...confirmEmailVerification.METADATA,
      template: confirmEmailVerification.METADATA.path,
      path: confirmEmailVerification.path(),
    },
    body,
  );
}
export namespace confirmEmailVerification {
  export type Body = Primitive<IBrokerDeskAdmin.IConfirmEmailVerification>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/email/verify/confirm",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/email/verify/confirm";
}
