/**
 * @packageDocumentation
 * @module api.functional.invoices.lines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskInvoice,
  IBrokerDeskInvoiceLine,
} from "../../../../../src/api/structures/BrokerDeskBilling";

/**
 * List the charge lines of an invoice.
 *
 * @param invoiceId Parent invoice identifier.
 * @returns The invoice's charge lines.
 *
 * @controller BrokerDeskBillingInvoiceController.lines
 * @path GET /invoices/:invoiceId/lines
 * @accessor api.functional.invoices.lines.lines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function lines(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
): Promise<lines.Output> {
  return PlainFetcher.fetch(connection, {
    ...lines.METADATA,
    template: lines.METADATA.path,
    path: lines.path(invoiceId),
  });
}
export namespace lines {
  export type Output = Primitive<Array<IBrokerDeskInvoiceLine>>;

  export const METADATA = {
    method: "GET",
    path: "/invoices/:invoiceId/lines",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/lines`;
}

/**
 * Add a charge line to an editable invoice.
 *
 * Allowed only while the parent invoice remains in `draft` status. The
 * applicable tax rate is frozen from the organization tax table and the
 * invoice totals are recomputed.
 *
 * @param invoiceId Parent invoice identifier.
 * @param body Charge line creation payload.
 * @returns The updated invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.addLine
 * @path POST /invoices/:invoiceId/lines
 * @accessor api.functional.invoices.lines.addLine
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addLine(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  body: addLine.Body,
): Promise<addLine.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...addLine.METADATA,
      template: addLine.METADATA.path,
      path: addLine.path(invoiceId),
    },
    body,
  );
}
export namespace addLine {
  export type Body = Primitive<IBrokerDeskInvoiceLine.ICreate>;
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "POST",
    path: "/invoices/:invoiceId/lines",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/lines`;
}

/**
 * Update a charge line on an editable invoice.
 *
 * @param invoiceId Parent invoice identifier.
 * @param lineId Target line identifier.
 * @param body Mutable line fields.
 * @returns The updated invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.updateLine
 * @path PUT /invoices/:invoiceId/lines/:lineId
 * @accessor api.functional.invoices.lines.updateLine
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateLine(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  lineId: string & tags.Format<"uuid">,
  body: updateLine.Body,
): Promise<updateLine.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateLine.METADATA,
      template: updateLine.METADATA.path,
      path: updateLine.path(invoiceId, lineId),
    },
    body,
  );
}
export namespace updateLine {
  export type Body = Primitive<IBrokerDeskInvoiceLine.IUpdate>;
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "PUT",
    path: "/invoices/:invoiceId/lines/:lineId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    invoiceId: string & tags.Format<"uuid">,
    lineId: string & tags.Format<"uuid">,
  ) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/lines/${encodeURIComponent(lineId?.toString() ?? "null")}`;
}

/**
 * Remove a charge line from an editable invoice.
 *
 * @param invoiceId Parent invoice identifier.
 * @param lineId Target line identifier.
 * @returns The updated invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.eraseLine
 * @path DELETE /invoices/:invoiceId/lines/:lineId
 * @accessor api.functional.invoices.lines.eraseLine
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseLine(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  lineId: string & tags.Format<"uuid">,
): Promise<eraseLine.Output> {
  return PlainFetcher.fetch(connection, {
    ...eraseLine.METADATA,
    template: eraseLine.METADATA.path,
    path: eraseLine.path(invoiceId, lineId),
  });
}
export namespace eraseLine {
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "DELETE",
    path: "/invoices/:invoiceId/lines/:lineId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    invoiceId: string & tags.Format<"uuid">,
    lineId: string & tags.Format<"uuid">,
  ) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/lines/${encodeURIComponent(lineId?.toString() ?? "null")}`;
}
