/**
 * @packageDocumentation
 * @module api.functional.organization
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as addresses from "./addresses/index";
