/**
 * @packageDocumentation
 * @module api.functional.clients.tags
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskClientTag } from "../../../../../src/api/structures/BrokerDeskCrmClient";

/**
 * List all active tags assigned to a client.
 *
 * @param clientId Primary key of the target client.
 * @returns The client's tag assignments.
 *
 * @controller BrokerDeskCrmClientController.tags
 * @path GET /clients/:clientId/tags
 * @accessor api.functional.clients.tags.tags
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function tags(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<tags.Output> {
  return PlainFetcher.fetch(connection, {
    ...tags.METADATA,
    template: tags.METADATA.path,
    path: tags.path(clientId),
  });
}
export namespace tags {
  export type Output = Primitive<Array<IBrokerDeskClientTag>>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/tags",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/tags`;
}

/**
 * Attach a tag to a client.
 *
 * Tag values are normalized (trimmed casing/whitespace); exact duplicates
 * per client are rejected.
 *
 * @param clientId Primary key of the target client.
 * @param body Tag creation payload.
 * @returns The created tag assignment.
 *
 * @controller BrokerDeskCrmClientController.createTag
 * @path POST /clients/:clientId/tags
 * @accessor api.functional.clients.tags.createTag
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createTag(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: createTag.Body,
): Promise<createTag.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createTag.METADATA,
      template: createTag.METADATA.path,
      path: createTag.path(clientId),
    },
    body,
  );
}
export namespace createTag {
  export type Body = Primitive<{ value: string }>;
  export type Output = Primitive<IBrokerDeskClientTag>;

  export const METADATA = {
    method: "POST",
    path: "/clients/:clientId/tags",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/tags`;
}

/**
 * Remove a tag from a client by soft-deleting the assignment row.
 *
 * @param clientId Primary key of the target client.
 * @param tagId Primary key of the tag assignment.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmClientController.eraseTag
 * @path DELETE /clients/:clientId/tags/:tagId
 * @accessor api.functional.clients.tags.eraseTag
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eraseTag(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  tagId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...eraseTag.METADATA,
    template: eraseTag.METADATA.path,
    path: eraseTag.path(clientId, tagId),
  });
}
export namespace eraseTag {
  export const METADATA = {
    method: "DELETE",
    path: "/clients/:clientId/tags/:tagId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    tagId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/tags/${encodeURIComponent(tagId?.toString() ?? "null")}`;
}
