/**
 * @packageDocumentation
 * @module api.functional.policies.documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPolicyDocument } from "../../../../../src/api/structures/BrokerDeskPolicyDocument";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List documents belonging to a policy.
 *
 * @param policyId Owning policy id.
 * @param body Search and pagination criteria.
 * @returns Paginated document summaries.
 *
 * @controller BrokerDeskPolicyDocumentController.index
 * @path PATCH /policies/:policyId/documents
 * @accessor api.functional.policies.documents.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(policyId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskPolicyDocument.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPolicyDocument.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/policies/:policyId/documents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/documents`;
}

/**
 * Retrieve a single policy document record.
 *
 * @param policyId Owning policy id.
 * @param documentId Target document id.
 * @returns The document record.
 *
 * @controller BrokerDeskPolicyDocumentController.at
 * @path GET /policies/:policyId/documents/:documentId
 * @accessor api.functional.policies.documents.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  documentId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(policyId, documentId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskPolicyDocument>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/documents/:documentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    documentId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/documents/${encodeURIComponent(documentId?.toString() ?? "null")}`;
}
