/**
 * @packageDocumentation
 * @module api.functional.document_templates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskDocumentTemplate,
  IPageIBrokerDeskDocumentTemplateISummary,
} from "../../../../src/api/structures/BrokerDeskDocument";

/**
 * List document templates in the organization's library.
 *
 * Returns a paginated, filterable listing of the wording library. Filter by
 * kind, locale, retirement state, or name substring to locate wordings when
 * generating paperwork.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated template summaries.
 *
 * @controller BrokerDeskDocumentTemplateController.index
 * @path PATCH /document-templates
 * @accessor api.functional.document_templates.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskDocumentTemplate.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskDocumentTemplateISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/document-templates",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/document-templates";
}

/**
 * Read one document template in full.
 *
 * Retrieves the complete wording including the markdown/HTML body with
 * {{variable}} placeholders so administrators can review or revise it.
 *
 * @param templateId Identifier of the target template.
 * @returns Full template read model.
 *
 * @controller BrokerDeskDocumentTemplateController.at
 * @path GET /document-templates/:templateId
 * @accessor api.functional.document_templates.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  templateId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(templateId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskDocumentTemplate.IBody>;

  export const METADATA = {
    method: "GET",
    path: "/document-templates/:templateId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (templateId: string & tags.Format<"uuid">) =>
    `/document-templates/${encodeURIComponent(templateId?.toString() ?? "null")}`;
}

/**
 * Create a new document template.
 *
 * Adds a wording to the organization's library. The kind and name pair is
 * unique per organization, preventing duplicate wordings of the same
 * paperwork type.
 *
 * @param body Template creation payload.
 * @returns Full template read model of the created wording.
 *
 * @controller BrokerDeskDocumentTemplateController.create
 * @path POST /document-templates
 * @accessor api.functional.document_templates.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskDocumentTemplate.ICreate>;
  export type Output = Primitive<IBrokerDeskDocumentTemplate.IBody>;

  export const METADATA = {
    method: "POST",
    path: "/document-templates",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/document-templates";
}

/**
 * Revise a document template.
 *
 * Updates the wording body, display name, or locale. Already-issued
 * documents keep the rendered content they were produced with; only future
 * renders use the revised wording.
 *
 * @param templateId Identifier of the target template.
 * @param body Partial update payload.
 * @returns Full template read model after revision.
 *
 * @controller BrokerDeskDocumentTemplateController.update
 * @path PUT /document-templates/:templateId
 * @accessor api.functional.document_templates.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  templateId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(templateId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskDocumentTemplate.IUpdate>;
  export type Output = Primitive<IBrokerDeskDocumentTemplate.IBody>;

  export const METADATA = {
    method: "PUT",
    path: "/document-templates/:templateId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (templateId: string & tags.Format<"uuid">) =>
    `/document-templates/${encodeURIComponent(templateId?.toString() ?? "null")}`;
}

/**
 * Retire a document template.
 *
 * Removes the template from future selection while historical documents
 * keep the rendered content they were produced with. Flipping retirement
 * restores availability without data loss.
 *
 * @param templateId Identifier of the target template.
 *
 * @controller BrokerDeskDocumentTemplateController.erase
 * @path DELETE /document-templates/:templateId
 * @accessor api.functional.document_templates.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  templateId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(templateId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/document-templates/:templateId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (templateId: string & tags.Format<"uuid">) =>
    `/document-templates/${encodeURIComponent(templateId?.toString() ?? "null")}`;
}

/**
 * Render paperwork from a template against an owner entity.
 *
 * Substitutes the template's {{variable}} placeholders with data resolved
 * from the referenced client, quote, policy, or invoice, stores the
 * rendered HTML/text as a new document rendition, and returns both the
 * filed document and the rendered content. The result may additionally be
 * materialized as a PDF placeholder.
 *
 * @param templateId Identifier of the template to render.
 * @param body Owner entity the placeholders resolve against.
 * @returns The filed document with its rendered content.
 *
 * @controller BrokerDeskDocumentTemplateController.render
 * @path POST /document-templates/:templateId/render
 * @accessor api.functional.document_templates.render
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function render(
  connection: IConnection,
  templateId: string & tags.Format<"uuid">,
  body: render.Body,
): Promise<render.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...render.METADATA,
      template: render.METADATA.path,
      path: render.path(templateId),
    },
    body,
  );
}
export namespace render {
  export type Body = Primitive<IBrokerDeskDocumentTemplate.IRenderRequest>;
  export type Output = Primitive<IBrokerDeskDocumentTemplate.IRendered>;

  export const METADATA = {
    method: "POST",
    path: "/document-templates/:templateId/render",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (templateId: string & tags.Format<"uuid">) =>
    `/document-templates/${encodeURIComponent(templateId?.toString() ?? "null")}/render`;
}
