/**
 * @packageDocumentation
 * @module api.functional.producers.me.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskProducerSession } from "../../../../../../src/api/structures/BrokerDeskActorsProducer";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the sign-in sessions of the authenticated producer.
 *
 * @param body Pagination criteria.
 * @returns Paginated session history of the caller.
 *
 * @controller BrokerDeskActorsProducerMeController.indexSessions
 * @path PATCH /producers/me/sessions
 * @accessor api.functional.producers.me.sessions.indexSessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexSessions(
  connection: IConnection,
  body: indexSessions.Body,
): Promise<indexSessions.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...indexSessions.METADATA,
      template: indexSessions.METADATA.path,
      path: indexSessions.path(),
    },
    body,
  );
}
export namespace indexSessions {
  export type Body = Primitive<IBrokerDeskProducerSession.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskProducerSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/producers/me/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/producers/me/sessions";
}
