/**
 * @packageDocumentation
 * @module api.functional.auth.guest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskGuest } from "../../../../../src/api/structures/BrokerDeskActorsGuest";

export * as sessions from "./sessions/index";

/**
 * Issue an anonymous guest session for a public-flow visitor.
 *
 * Creates the guest anchor if the visitor does not already hold one and
 * appends a fresh short-lived session capturing the device context. Guest
 * sessions carry no credentials and expire mandatorily.
 *
 * @param body Device context (ip, href, referrer) of the anonymous visit.
 * @returns The guest anchor with a freshly issued anonymous JWT pair.
 *
 * @controller BrokerDeskActorsGuestAuthController.join
 * @path POST /auth/guest/join
 * @accessor api.functional.auth.guest.join
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function join(
  connection: IConnection,
  body: join.Body,
): Promise<join.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...join.METADATA,
      template: join.METADATA.path,
      path: join.path(),
    },
    body,
  );
}
export namespace join {
  export type Body = Primitive<IBrokerDeskGuest.IJoin>;
  export type Output = Primitive<IBrokerDeskGuest.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/guest/join",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/guest/join";
}
