/**
 * @packageDocumentation
 * @module api.functional.carriers.appointments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskCarrierAppointment,
  IPageIBrokerDeskCarrierAppointmentISummary,
} from "../../../../../src/api/structures/BrokerDeskCatalogueCarrier";

/**
 * List appointments for a carrier with pagination and filters.
 *
 * Supports compliance review with status filtering and an
 * expiring-within-days window that surfaces appointments whose expiry is
 * imminent.
 *
 * @param carrierId Parent carrier id.
 * @param body Pagination and filter criteria.
 * @returns Paginated appointment summary list.
 *
 * @controller BrokerDeskCatalogueCarrierAppointmentController.index
 * @path PATCH /carriers/:carrierId/appointments
 * @accessor api.functional.carriers.appointments.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(carrierId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCarrierAppointment.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskCarrierAppointmentISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/carriers/:carrierId/appointments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (carrierId: string & tags.Format<"uuid">) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}/appointments`;
}

/**
 * Create an appointment of this carrier to the organization.
 *
 * ADMIN-only operation recording the start of a placing-authority term.
 *
 * @param carrierId Parent carrier id.
 * @param body Appointment creation attributes.
 * @returns The newly created appointment.
 *
 * @controller BrokerDeskCatalogueCarrierAppointmentController.create
 * @path POST /carriers/:carrierId/appointments
 * @accessor api.functional.carriers.appointments.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(carrierId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCarrierAppointment.ICreate>;
  export type Output = Primitive<IBrokerDeskCarrierAppointment>;

  export const METADATA = {
    method: "POST",
    path: "/carriers/:carrierId/appointments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (carrierId: string & tags.Format<"uuid">) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}/appointments`;
}

/**
 * Fetch an appointment by id.
 *
 * @param carrierId Parent carrier id.
 * @param appointmentId Target appointment id.
 * @returns The appointment detail.
 *
 * @controller BrokerDeskCatalogueCarrierAppointmentController.at
 * @path GET /carriers/:carrierId/appointments/:appointmentId
 * @accessor api.functional.carriers.appointments.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  appointmentId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(carrierId, appointmentId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCarrierAppointment>;

  export const METADATA = {
    method: "GET",
    path: "/carriers/:carrierId/appointments/:appointmentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    carrierId: string & tags.Format<"uuid">,
    appointmentId: string & tags.Format<"uuid">,
  ) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}/appointments/${encodeURIComponent(appointmentId?.toString() ?? "null")}`;
}

/**
 * Update an appointment's status or term dates.
 *
 * Typical use is a renewal pushing expires_at forward or a termination
 * changing status.
 *
 * @param carrierId Parent carrier id.
 * @param appointmentId Target appointment id.
 * @param body Fields to update.
 * @returns The updated appointment.
 *
 * @controller BrokerDeskCatalogueCarrierAppointmentController.update
 * @path PUT /carriers/:carrierId/appointments/:appointmentId
 * @accessor api.functional.carriers.appointments.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  appointmentId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(carrierId, appointmentId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCarrierAppointment.IUpdate>;
  export type Output = Primitive<IBrokerDeskCarrierAppointment>;

  export const METADATA = {
    method: "PUT",
    path: "/carriers/:carrierId/appointments/:appointmentId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    carrierId: string & tags.Format<"uuid">,
    appointmentId: string & tags.Format<"uuid">,
  ) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}/appointments/${encodeURIComponent(appointmentId?.toString() ?? "null")}`;
}

/**
 * Soft-delete an appointment, preserving historical audit trails.
 *
 * @param carrierId Parent carrier id.
 * @param appointmentId Target appointment id.
 *
 * @controller BrokerDeskCatalogueCarrierAppointmentController.erase
 * @path DELETE /carriers/:carrierId/appointments/:appointmentId
 * @accessor api.functional.carriers.appointments.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  appointmentId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(carrierId, appointmentId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/carriers/:carrierId/appointments/:appointmentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    carrierId: string & tags.Format<"uuid">,
    appointmentId: string & tags.Format<"uuid">,
  ) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}/appointments/${encodeURIComponent(appointmentId?.toString() ?? "null")}`;
}
