/**
 * @packageDocumentation
 * @module api.functional.admin.producers.licences
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskProducerLicence } from "../../../../../../src/api/structures/BrokerDeskActorsProducer";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the licences held by a producer.
 *
 * @param producerId Parent producer identifier.
 * @param body Search, filter, and pagination criteria including compliance views.
 * @returns Paginated licence summaries.
 *
 * @controller BrokerDeskActorsAdminProducerLicencesController.index
 * @path PATCH /admin/producers/:producerId/licences
 * @accessor api.functional.admin.producers.licences.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(producerId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskProducerLicence.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskProducerLicence.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/producers/:producerId/licences",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (producerId: string & tags.Format<"uuid">) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}/licences`;
}

/**
 * Register a provincial licence for a producer.
 *
 * @param producerId Parent producer identifier.
 * @param body Licence fields (province, type, number, validity, status).
 * @returns The newly registered licence.
 *
 * @controller BrokerDeskActorsAdminProducerLicencesController.create
 * @path POST /admin/producers/:producerId/licences
 * @accessor api.functional.admin.producers.licences.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(producerId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskProducerLicence.ICreate>;
  export type Output = Primitive<IBrokerDeskProducerLicence>;

  export const METADATA = {
    method: "POST",
    path: "/admin/producers/:producerId/licences",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (producerId: string & tags.Format<"uuid">) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}/licences`;
}

/**
 * Retrieve one licence in detail.
 *
 * @param producerId Parent producer identifier.
 * @param licenceId Target licence identifier.
 * @returns The licence record.
 *
 * @controller BrokerDeskActorsAdminProducerLicencesController.at
 * @path GET /admin/producers/:producerId/licences/:licenceId
 * @accessor api.functional.admin.producers.licences.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  licenceId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(producerId, licenceId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskProducerLicence>;

  export const METADATA = {
    method: "GET",
    path: "/admin/producers/:producerId/licences/:licenceId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    producerId: string & tags.Format<"uuid">,
    licenceId: string & tags.Format<"uuid">,
  ) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}/licences/${encodeURIComponent(licenceId?.toString() ?? "null")}`;
}

/**
 * Update a licence record.
 *
 * Renewals extend the validity window; suspensions and revocations are
 * recorded through the status field.
 *
 * @param producerId Parent producer identifier.
 * @param licenceId Target licence identifier.
 * @param body Mutable licence fields.
 * @returns The updated licence record.
 *
 * @controller BrokerDeskActorsAdminProducerLicencesController.update
 * @path PUT /admin/producers/:producerId/licences/:licenceId
 * @accessor api.functional.admin.producers.licences.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  licenceId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(producerId, licenceId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskProducerLicence.IUpdate>;
  export type Output = Primitive<IBrokerDeskProducerLicence>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/producers/:producerId/licences/:licenceId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    producerId: string & tags.Format<"uuid">,
    licenceId: string & tags.Format<"uuid">,
  ) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}/licences/${encodeURIComponent(licenceId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a licence record.
 *
 * Withdrawn licences remain available for historical compliance auditing.
 *
 * @param producerId Parent producer identifier.
 * @param licenceId Target licence identifier.
 *
 * @controller BrokerDeskActorsAdminProducerLicencesController.erase
 * @path DELETE /admin/producers/:producerId/licences/:licenceId
 * @accessor api.functional.admin.producers.licences.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  licenceId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(producerId, licenceId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/admin/producers/:producerId/licences/:licenceId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    producerId: string & tags.Format<"uuid">,
    licenceId: string & tags.Format<"uuid">,
  ) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}/licences/${encodeURIComponent(licenceId?.toString() ?? "null")}`;
}
