/**
 * @packageDocumentation
 * @module api.functional.quotes
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskQuote } from "../../../../src/api/structures/BrokerDeskQuoting";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as lines from "./lines/index";
export * as submissions from "./submissions/index";

/**
 * List quotations matching search and filter criteria.
 *
 * Returns a paginated page of quote summaries scoped to the caller's
 * organization, optionally filtered by client, producer, status,
 * expiry window, or free-text search.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated quote summaries.
 *
 * @controller BrokerDeskQuotingQuoteController.index
 * @path PATCH /quotes
 * @accessor api.functional.quotes.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskQuote.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskQuote.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/quotes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/quotes";
}

/**
 * Create a new draft quotation for a client.
 *
 * The creating producer is resolved from the JWT identity; optional
 * initial comparative lines may be attached in the same request.
 *
 * @param body Quote creation payload.
 * @returns The newly created quotation.
 *
 * @controller BrokerDeskQuotingQuoteController.create
 * @path POST /quotes
 * @accessor api.functional.quotes.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskQuote.ICreate>;
  export type Output = Primitive<IBrokerDeskQuote>;

  export const METADATA = {
    method: "POST",
    path: "/quotes",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/quotes";
}

/**
 * Fetch one quotation in full detail.
 *
 * Loads the quote with its comparative lines and carrier submissions,
 * enforcing tenant isolation on the lookup.
 *
 * @param quoteId Identifier of the target quotation.
 * @returns The full quotation record.
 *
 * @controller BrokerDeskQuotingQuoteController.at
 * @path GET /quotes/:quoteId
 * @accessor api.functional.quotes.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(quoteId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskQuote>;

  export const METADATA = {
    method: "GET",
    path: "/quotes/:quoteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}`;
}

/**
 * Update a quotation's mutable fields or workflow status.
 *
 * Status transitions follow the mandated flow draft -> priced ->
 * submitted -> bound | declined | expired.
 *
 * @param quoteId Identifier of the target quotation.
 * @param body Fields to update, all optional.
 * @returns The updated quotation.
 *
 * @controller BrokerDeskQuotingQuoteController.update
 * @path PUT /quotes/:quoteId
 * @accessor api.functional.quotes.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(quoteId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskQuote.IUpdate>;
  export type Output = Primitive<IBrokerDeskQuote>;

  export const METADATA = {
    method: "PUT",
    path: "/quotes/:quoteId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a quotation, preserving its rows for audit history.
 *
 * @param quoteId Identifier of the target quotation.
 *
 * @controller BrokerDeskQuotingQuoteController.erase
 * @path DELETE /quotes/:quoteId
 * @accessor api.functional.quotes.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(quoteId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/quotes/:quoteId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}`;
}

/**
 * Calculate premiums, broker fees, taxes, and totals for the quote.
 *
 * Uses each attached product's formula configuration where available
 * and always permits manual overrides per line; refreshes the quote's
 * CAD totals and moves a draft quote to priced status.
 *
 * @param quoteId Identifier of the target quotation.
 * @param body Per-line pricing inputs with optional manual overrides.
 * @returns Recalculated totals and refreshed line summaries.
 *
 * @controller BrokerDeskQuotingQuoteController.price
 * @path POST /quotes/:quoteId/price
 * @accessor api.functional.quotes.price
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function price(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: price.Body,
): Promise<price.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...price.METADATA,
      template: price.METADATA.path,
      path: price.path(quoteId),
    },
    body,
  );
}
export namespace price {
  export type Body = Primitive<IBrokerDeskQuote.IPrice>;
  export type Output = Primitive<IBrokerDeskQuote.IPriceResult>;

  export const METADATA = {
    method: "POST",
    path: "/quotes/:quoteId/price",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/price`;
}

/**
 * Bind the accepted quote line into a new policy, transactionally.
 *
 * Marks the chosen line accepted (clearing siblings), transitions the
 * quote to bound status, and creates the originating policy with
 * coverage schedule lines mirrored from the quote line's coverage
 * selections. Idempotency is guaranteed by rejecting re-binding an
 * already-bound quote.
 *
 * @param quoteId Identifier of the target quotation.
 * @param body The accepted quote line identifier.
 * @returns The created policy and the updated quote.
 *
 * @controller BrokerDeskQuotingQuoteController.bind
 * @path POST /quotes/:quoteId/bind
 * @accessor api.functional.quotes.bind
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function bind(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: bind.Body,
): Promise<bind.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...bind.METADATA,
      template: bind.METADATA.path,
      path: bind.path(quoteId),
    },
    body,
  );
}
export namespace bind {
  export type Body = Primitive<IBrokerDeskQuote.IBind>;
  export type Output = Primitive<IBrokerDeskQuote.IBindResult>;

  export const METADATA = {
    method: "POST",
    path: "/quotes/:quoteId/bind",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/bind`;
}
