/**
 * @packageDocumentation
 * @module api.functional.commission_statements
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskCommissionStatement } from "../../../../src/api/structures/BrokerDeskBilling";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as mark_paid from "./mark_paid/index";

/**
 * List commission statements.
 *
 * Admin-facing listing filterable by producer, settlement state, and
 * period start range.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated statement summaries.
 *
 * @controller BrokerDeskBillingCommissionStatementController.index
 * @path PATCH /commission-statements
 * @accessor api.functional.commission_statements.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCommissionStatement.IRequest>;
  export type Output = Primitive<
    IPage<IBrokerDeskCommissionStatement.ISummary>
  >;

  export const METADATA = {
    method: "PATCH",
    path: "/commission-statements",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/commission-statements";
}

/**
 * Fetch a single commission statement with its member commissions.
 *
 * @param statementId Target statement identifier.
 * @returns The complete statement record.
 *
 * @controller BrokerDeskBillingCommissionStatementController.at
 * @path GET /commission-statements/:statementId
 * @accessor api.functional.commission_statements.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  statementId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(statementId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCommissionStatement>;

  export const METADATA = {
    method: "GET",
    path: "/commission-statements/:statementId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (statementId: string & tags.Format<"uuid">) =>
    `/commission-statements/${encodeURIComponent(statementId?.toString() ?? "null")}`;
}

/**
 * Issue (generate) a commission statement for a producer and period.
 *
 * Aggregates the unsettled commissions of the producer within the given
 * period span, freezes the agency and producer totals onto the statement,
 * and back-links the member commissions. Duplicate statements for the
 * same producer and period span are rejected.
 *
 * @param body Statement generation payload (producer + period span).
 * @returns The created statement.
 *
 * @controller BrokerDeskBillingCommissionStatementController.create
 * @path POST /commission-statements
 * @accessor api.functional.commission_statements.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCommissionStatement.ICreate>;
  export type Output = Primitive<IBrokerDeskCommissionStatement>;

  export const METADATA = {
    method: "POST",
    path: "/commission-statements",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/commission-statements";
}
