/**
 * @packageDocumentation
 * @module api.functional.documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskDocument,
  IPageIBrokerDeskDocumentISummary,
} from "../../../../src/api/structures/BrokerDeskDocument";

export * as versions from "./versions/index";

/**
 * List filed documents.
 *
 * Returns a paginated, filterable listing of the document registry. Filter
 * by owner (type and id), business kind, filename substring, or originating
 * template to browse a client's paperwork trail or an entity's attachments.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated document summaries.
 *
 * @controller BrokerDeskDocumentController.index
 * @path PATCH /documents
 * @accessor api.functional.documents.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskDocument.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskDocumentISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/documents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/documents";
}

/**
 * Read one filed document in detail.
 *
 * Retrieves the active rendition's metadata including the storage path and
 * integrity checksum for tamper detection and deduplication checks.
 *
 * @param documentId Identifier of the target document.
 * @returns Detailed document read model.
 *
 * @controller BrokerDeskDocumentController.at
 * @path GET /documents/:documentId
 * @accessor api.functional.documents.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(documentId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskDocument.IDetail>;

  export const METADATA = {
    method: "GET",
    path: "/documents/:documentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (documentId: string & tags.Format<"uuid">) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}`;
}

/**
 * Upload (file) a new document.
 *
 * Files a document against exactly one polymorphic owner fixed at upload
 * time; the binding never migrates. Filing attribution records which staff
 * actor category performed the upload, and the initial rendition becomes
 * version 1.
 *
 * @param body Upload payload with owner binding and file content.
 * @returns Summary of the filed document.
 *
 * @controller BrokerDeskDocumentController.create
 * @path POST /documents
 * @accessor api.functional.documents.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskDocument.ICreate>;
  export type Output = Primitive<IBrokerDeskDocument.ISummary>;

  export const METADATA = {
    method: "POST",
    path: "/documents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/documents";
}

/**
 * Replace a document's current rendition.
 *
 * Re-uploads the file, archiving the outgoing rendition as an immutable
 * historical version and incrementing the active version number. Historical
 * renditions remain fully retrievable through the version history.
 *
 * @param documentId Identifier of the target document.
 * @param body Replacement payload with new file content.
 * @returns Summary of the document after replacement.
 *
 * @controller BrokerDeskDocumentController.update
 * @path PUT /documents/:documentId
 * @accessor api.functional.documents.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(documentId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskDocument.IReplace>;
  export type Output = Primitive<IBrokerDeskDocument.ISummary>;

  export const METADATA = {
    method: "PUT",
    path: "/documents/:documentId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (documentId: string & tags.Format<"uuid">) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a filed document.
 *
 * Hides the document from active listings while preserving the row and its
 * version history for audit and recovery.
 *
 * @param documentId Identifier of the target document.
 *
 * @controller BrokerDeskDocumentController.erase
 * @path DELETE /documents/:documentId
 * @accessor api.functional.documents.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(documentId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/documents/:documentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (documentId: string & tags.Format<"uuid">) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}`;
}

/**
 * Download the current rendition of a document.
 *
 * Streams the active rendition's content together with its filename, MIME
 * type, byte size, and integrity checksum so consumers can verify content
 * integrity, supporting PIPEDA-aware integrity expectations.
 *
 * @param documentId Identifier of the target document.
 * @returns Download payload with base64-encoded content and checksum.
 *
 * @controller BrokerDeskDocumentController.download
 * @path GET /documents/:documentId/download
 * @accessor api.functional.documents.download
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function download(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
): Promise<download.Output> {
  return PlainFetcher.fetch(connection, {
    ...download.METADATA,
    template: download.METADATA.path,
    path: download.path(documentId),
  });
}
export namespace download {
  export type Output = Primitive<IBrokerDeskDocument.IDownload>;

  export const METADATA = {
    method: "GET",
    path: "/documents/:documentId/download",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (documentId: string & tags.Format<"uuid">) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}/download`;
}
