/**
 * @packageDocumentation
 * @module api.functional.auth.admin.email
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as verify from "./verify/index";
