/**
 * @packageDocumentation
 * @module api.functional.clients.activities
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskActivity,
  IPageIBrokerDeskActivitySummary,
} from "../../../../../src/api/structures/BrokerDeskCrmActivity";

/**
 * List activities on a client's timeline.
 *
 * Supports type filtering, free-text subject/body search, and occurred_at
 * range filters.
 *
 * @param clientId Primary key of the parent client.
 * @returns The client's activities, newest first.
 *
 * @controller BrokerDeskCrmActivityController.index
 * @path GET /clients/:clientId/activities
 * @accessor api.functional.clients.activities.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(clientId),
  });
}
export namespace index {
  export type Output = Primitive<IPageIBrokerDeskActivitySummary>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/activities",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/activities`;
}

/**
 * Read one activity entry in full detail, including resolved authorship.
 *
 * @param clientId Primary key of the parent client.
 * @param activityId Primary key of the activity.
 * @returns The activity detail.
 *
 * @controller BrokerDeskCrmActivityController.at
 * @path GET /clients/:clientId/activities/:activityId
 * @accessor api.functional.clients.activities.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  activityId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(clientId, activityId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskActivity>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/activities/:activityId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    activityId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/activities/${encodeURIComponent(activityId?.toString() ?? "null")}`;
}

/**
 * Log a new activity on a client's timeline.
 *
 * The author is resolved from the acting JWT identity and persisted via the
 * matching producer or CSR authorship row; occurred_at may be back-dated
 * for batch logging.
 *
 * @param clientId Primary key of the parent client.
 * @param body Activity creation payload.
 * @returns The created activity.
 *
 * @controller BrokerDeskCrmActivityController.create
 * @path POST /clients/:clientId/activities
 * @accessor api.functional.clients.activities.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(clientId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskActivity.ICreate>;
  export type Output = Primitive<IBrokerDeskActivity>;

  export const METADATA = {
    method: "POST",
    path: "/clients/:clientId/activities",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/activities`;
}

/**
 * Revise an activity entry.
 *
 * @param clientId Primary key of the parent client.
 * @param activityId Primary key of the activity.
 * @param body Fields to update, all optional.
 * @returns The updated activity.
 *
 * @controller BrokerDeskCrmActivityController.update
 * @path PUT /clients/:clientId/activities/:activityId
 * @accessor api.functional.clients.activities.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  activityId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(clientId, activityId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskActivity.IUpdate>;
  export type Output = Primitive<IBrokerDeskActivity>;

  export const METADATA = {
    method: "PUT",
    path: "/clients/:clientId/activities/:activityId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    activityId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/activities/${encodeURIComponent(activityId?.toString() ?? "null")}`;
}

/**
 * Soft-delete an erroneous activity entry, hiding it from the timeline
 * while retaining the historical record.
 *
 * @param clientId Primary key of the parent client.
 * @param activityId Primary key of the activity.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmActivityController.erase
 * @path DELETE /clients/:clientId/activities/:activityId
 * @accessor api.functional.clients.activities.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  activityId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(clientId, activityId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/clients/:clientId/activities/:activityId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    activityId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/activities/${encodeURIComponent(activityId?.toString() ?? "null")}`;
}
