/**
 * @packageDocumentation
 * @module api.functional.tasks
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskTask,
  IPageIBrokerDeskTaskSummary,
} from "../../../../src/api/structures/BrokerDeskCrmTask";

/**
 * List and filter tasks of the acting organization.
 *
 * Supports status, client, policy, due-date range, and free-text title
 * filters with pagination.
 *
 * @param body Search and filter criteria.
 * @returns Paginated task summaries.
 *
 * @controller BrokerDeskCrmTaskController.index
 * @path PATCH /tasks
 * @accessor api.functional.tasks.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskTask.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskTaskSummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/tasks",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/tasks";
}

/**
 * List the tasks assigned to the acting staff member.
 *
 * Returns the personal queue resolved through whichever assignment junction
 * matches the acting role.
 *
 * @returns The acting staff member's assigned tasks.
 *
 * @controller BrokerDeskCrmTaskController.me
 * @path GET /tasks/me
 * @accessor api.functional.tasks.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = Primitive<IBrokerDeskTask.IMyQueue>;

  export const METADATA = {
    method: "GET",
    path: "/tasks/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/tasks/me";
}

/**
 * Read one task in full detail, including anchors and resolved assignee.
 *
 * @param taskId Primary key of the task.
 * @returns The task detail.
 *
 * @controller BrokerDeskCrmTaskController.at
 * @path GET /tasks/:taskId
 * @accessor api.functional.tasks.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  taskId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(taskId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskTask>;

  export const METADATA = {
    method: "GET",
    path: "/tasks/:taskId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (taskId: string & tags.Format<"uuid">) =>
    `/tasks/${encodeURIComponent(taskId?.toString() ?? "null")}`;
}

/**
 * Create a task and bind its assignee.
 *
 * Exactly one assignee reference must be supplied; the owning organization
 * comes from the acting JWT identity.
 *
 * @param body Task creation payload.
 * @returns The created task.
 *
 * @controller BrokerDeskCrmTaskController.create
 * @path POST /tasks
 * @accessor api.functional.tasks.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskTask.ICreate>;
  export type Output = Primitive<IBrokerDeskTask>;

  export const METADATA = {
    method: "POST",
    path: "/tasks",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/tasks";
}

/**
 * Update a task: adjust content, due date, status, or reassign.
 *
 * Reassignment retires the prior assignment row and creates the
 * replacement for the new role kind.
 *
 * @param taskId Primary key of the task.
 * @param body Fields to update, all optional.
 * @returns The updated task.
 *
 * @controller BrokerDeskCrmTaskController.update
 * @path PUT /tasks/:taskId
 * @accessor api.functional.tasks.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  taskId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(taskId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskTask.IUpdate>;
  export type Output = Primitive<IBrokerDeskTask>;

  export const METADATA = {
    method: "PUT",
    path: "/tasks/:taskId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (taskId: string & tags.Format<"uuid">) =>
    `/tasks/${encodeURIComponent(taskId?.toString() ?? "null")}`;
}

/**
 * Delete a task record.
 *
 * @param taskId Primary key of the task.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmTaskController.erase
 * @path DELETE /tasks/:taskId
 * @accessor api.functional.tasks.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  taskId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(taskId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/tasks/:taskId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (taskId: string & tags.Format<"uuid">) =>
    `/tasks/${encodeURIComponent(taskId?.toString() ?? "null")}`;
}
