/**
 * @packageDocumentation
 * @module api.functional.quotes.submissions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskSubmission } from "../../../../../src/api/structures/BrokerDeskQuoting";
import type { IPage } from "../../../../../src/api/structures/IPage";

export * as messages from "./messages/index";

/**
 * List carrier submissions for a quotation.
 *
 * Returns a paginated page of submission summaries, optionally
 * filtered by carrier or workflow status.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param body Search and pagination criteria.
 * @returns Paginated submission summaries.
 *
 * @controller BrokerDeskQuotingSubmissionController.index
 * @path PATCH /quotes/:quoteId/submissions
 * @accessor api.functional.quotes.submissions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(quoteId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskSubmission.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskSubmission.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/quotes/:quoteId/submissions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions`;
}

/**
 * Open a courtship thread with a carrier for a quotation.
 *
 * Enforces the at-most-one-submission-per-carrier-per-quote rule; each
 * status transition raises a notification for interested staff.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param body Submission creation payload.
 * @returns The created submission.
 *
 * @controller BrokerDeskQuotingSubmissionController.create
 * @path POST /quotes/:quoteId/submissions
 * @accessor api.functional.quotes.submissions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(quoteId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskSubmission.ICreate>;
  export type Output = Primitive<IBrokerDeskSubmission>;

  export const METADATA = {
    method: "POST",
    path: "/quotes/:quoteId/submissions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions`;
}

/**
 * Fetch one carrier submission with its conversation history.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param submissionId Identifier of the target submission.
 * @returns The full submission record.
 *
 * @controller BrokerDeskQuotingSubmissionController.at
 * @path GET /quotes/:quoteId/submissions/:submissionId
 * @accessor api.functional.quotes.submissions.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  submissionId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(quoteId, submissionId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskSubmission>;

  export const METADATA = {
    method: "GET",
    path: "/quotes/:quoteId/submissions/:submissionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    submissionId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions/${encodeURIComponent(submissionId?.toString() ?? "null")}`;
}

/**
 * Advance a submission's workflow status or capture carrier reference
 * and response details.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param submissionId Identifier of the target submission.
 * @param body Fields to update, all optional.
 * @returns The updated submission.
 *
 * @controller BrokerDeskQuotingSubmissionController.update
 * @path PUT /quotes/:quoteId/submissions/:submissionId
 * @accessor api.functional.quotes.submissions.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  submissionId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(quoteId, submissionId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskSubmission.IUpdate>;
  export type Output = Primitive<IBrokerDeskSubmission>;

  export const METADATA = {
    method: "PUT",
    path: "/quotes/:quoteId/submissions/:submissionId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    submissionId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions/${encodeURIComponent(submissionId?.toString() ?? "null")}`;
}
