/**
 * @packageDocumentation
 * @module api.functional.auth.csr.password
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as reset from "./reset/index";
