/**
 * @packageDocumentation
 * @module api.functional.policies.renewal_candidates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskPolicyRenewalCandidate } from "../../../../../src/api/structures/BrokerDeskPolicyRenewalCandidate";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List policies with term ends within the given number of days, for the
 * automated renewal candidate workflow.
 *
 * @param body Criteria including the lookahead window in days.
 * @returns Paginated renewal candidate policy summaries.
 *
 * @controller BrokerDeskPolicyPolicyController.renewalCandidates
 * @path PATCH /policies/renewal-candidates
 * @accessor api.functional.policies.renewal_candidates.renewalCandidates
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function renewalCandidates(
  connection: IConnection,
  body: renewalCandidates.Body,
): Promise<renewalCandidates.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...renewalCandidates.METADATA,
      template: renewalCandidates.METADATA.path,
      path: renewalCandidates.path(),
    },
    body,
  );
}
export namespace renewalCandidates {
  export type Body = Primitive<IBrokerDeskPolicyRenewalCandidate.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPolicyRenewalCandidate>>;

  export const METADATA = {
    method: "PATCH",
    path: "/policies/renewal-candidates",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/policies/renewal-candidates";
}
