/**
 * @packageDocumentation
 * @module api.functional.policies.endorsements
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPolicyEndorsement } from "../../../../../src/api/structures/BrokerDeskPolicy";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List endorsements of a policy, optionally filtered by status.
 *
 * @param policyId Owning policy id.
 * @param body Search criteria.
 * @returns Paginated endorsement summaries.
 *
 * @controller BrokerDeskPolicyEndorsementController.index
 * @path PATCH /policies/:policyId/endorsements
 * @accessor api.functional.policies.endorsements.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(policyId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskPolicyEndorsement.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPolicyEndorsement.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/policies/:policyId/endorsements",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/endorsements`;
}

/**
 * Retrieve a single endorsement record.
 *
 * @param policyId Owning policy id.
 * @param endorsementId Target endorsement id.
 * @returns The endorsement record.
 *
 * @controller BrokerDeskPolicyEndorsementController.at
 * @path GET /policies/:policyId/endorsements/:endorsementId
 * @accessor api.functional.policies.endorsements.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  endorsementId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(policyId, endorsementId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskPolicyEndorsement>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/endorsements/:endorsementId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    endorsementId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/endorsements/${encodeURIComponent(endorsementId?.toString() ?? "null")}`;
}

/**
 * Create a draft endorsement amending the policy mid-term.
 *
 * The effective date must fall within the parent policy term. The acting
 * CSR is attributed from the JWT identity, never from the request body.
 *
 * @param policyId Owning policy id.
 * @param body Endorsement creation payload.
 * @returns The newly created draft endorsement.
 *
 * @controller BrokerDeskPolicyEndorsementController.create
 * @path POST /policies/:policyId/endorsements
 * @accessor api.functional.policies.endorsements.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(policyId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskPolicyEndorsement.ICreate>;
  export type Output = Primitive<IBrokerDeskPolicyEndorsement>;

  export const METADATA = {
    method: "POST",
    path: "/policies/:policyId/endorsements",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/endorsements`;
}

/**
 * Update a draft endorsement. Issued endorsements are immutable apart
 * from soft deletion.
 *
 * @param policyId Owning policy id.
 * @param endorsementId Target endorsement id.
 * @param body Fields to update; all optional.
 * @returns The updated endorsement.
 *
 * @controller BrokerDeskPolicyEndorsementController.update
 * @path PUT /policies/:policyId/endorsements/:endorsementId
 * @accessor api.functional.policies.endorsements.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  endorsementId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(policyId, endorsementId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskPolicyEndorsement.IUpdate>;
  export type Output = Primitive<IBrokerDeskPolicyEndorsement>;

  export const METADATA = {
    method: "PUT",
    path: "/policies/:policyId/endorsements/:endorsementId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    endorsementId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/endorsements/${encodeURIComponent(endorsementId?.toString() ?? "null")}`;
}

/**
 * Issue (finalize) a draft endorsement, applying its premium and fee
 * deltas to the in-force policy.
 *
 * @param policyId Owning policy id.
 * @param endorsementId Target endorsement id.
 * @returns The issued endorsement.
 *
 * @controller BrokerDeskPolicyEndorsementController.issue
 * @path POST /policies/:policyId/endorsements/:endorsementId/issue
 * @accessor api.functional.policies.endorsements.issue
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function issue(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  endorsementId: string & tags.Format<"uuid">,
): Promise<issue.Output> {
  return PlainFetcher.fetch(connection, {
    ...issue.METADATA,
    template: issue.METADATA.path,
    path: issue.path(policyId, endorsementId),
  });
}
export namespace issue {
  export type Output = Primitive<IBrokerDeskPolicyEndorsement>;

  export const METADATA = {
    method: "POST",
    path: "/policies/:policyId/endorsements/:endorsementId/issue",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    endorsementId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/endorsements/${encodeURIComponent(endorsementId?.toString() ?? "null")}/issue`;
}
