/**
 * @packageDocumentation
 * @module api.functional.products
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskProduct,
  IPageIBrokerDeskProductISummary,
} from "../../../../src/api/structures/BrokerDeskCatalogueProduct";

export * as commission_schedule from "./commission_schedule/index";
export * as coverage_items from "./coverage_items/index";

/**
 * List products with pagination, search, and filters.
 *
 * Filterable by carrier, line of business, and active flag to support
 * comparative quote assembly and catalogue browsing.
 *
 * @param body Pagination and filter criteria.
 * @returns Paginated product summary list.
 *
 * @controller BrokerDeskCatalogueProductController.index
 * @path PATCH /products
 * @accessor api.functional.products.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskProduct.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskProductISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/products",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/products";
}

/**
 * Create a new product under a carrier.
 *
 * ADMIN-only operation; the line-of-business classification is fixed at
 * creation because downstream quoting and policy records depend on it.
 *
 * @param body Product creation attributes.
 * @returns The newly created product.
 *
 * @controller BrokerDeskCatalogueProductController.create
 * @path POST /products
 * @accessor api.functional.products.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskProduct.ICreate>;
  export type Output = Primitive<IBrokerDeskProduct>;

  export const METADATA = {
    method: "POST",
    path: "/products",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/products";
}

/**
 * Fetch a product by id.
 *
 * Returns the full product record including coverage-item summaries and the
 * default commission schedule when present.
 *
 * @param productId Target product id.
 * @returns The product detail.
 *
 * @controller BrokerDeskCatalogueProductController.at
 * @path GET /products/:productId
 * @accessor api.functional.products.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(productId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskProduct>;

  export const METADATA = {
    method: "GET",
    path: "/products/:productId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}`;
}

/**
 * Update a product's attributes.
 *
 * Eligibility rules and the rating schema are replaced wholesale when
 * provided; deactivation removes the product from future quote selection
 * while historical references are preserved.
 *
 * @param productId Target product id.
 * @param body Fields to update.
 * @returns The updated product.
 *
 * @controller BrokerDeskCatalogueProductController.update
 * @path PUT /products/:productId
 * @accessor api.functional.products.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(productId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskProduct.IUpdate>;
  export type Output = Primitive<IBrokerDeskProduct>;

  export const METADATA = {
    method: "PUT",
    path: "/products/:productId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}`;
}

/**
 * Delete a product catalogue entry.
 *
 * Historical quote lines, submissions, policies, and commissions retain
 * their product references for audit continuity.
 *
 * @param productId Target product id.
 *
 * @controller BrokerDeskCatalogueProductController.erase
 * @path DELETE /products/:productId
 * @accessor api.functional.products.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(productId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/products/:productId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}`;
}
