/**
 * @packageDocumentation
 * @module api.functional.dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as revenue from "./revenue/index";
