/**
 * @packageDocumentation
 * @module api.functional.invoices
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskInvoice } from "../../../../src/api/structures/BrokerDeskBilling";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as lines from "./lines/index";

/**
 * List invoices for the organization.
 *
 * Returns a paginated, filterable listing of client invoices. Supports
 * filtering by client, policy, status, issue-date range, and overdue-only,
 * plus sorting for aging and collection workflows. Soft-deleted invoices
 * are excluded.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated invoice summaries.
 *
 * @controller BrokerDeskBillingInvoiceController.index
 * @path PATCH /invoices
 * @accessor api.functional.invoices.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskInvoice.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskInvoice.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/invoices",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/invoices";
}

/**
 * Fetch a single invoice with lines and payments.
 *
 * Loads the full invoice header together with its charge lines and
 * recorded payments so balances can be reconciled in one call.
 *
 * @param invoiceId Target invoice identifier.
 * @returns The complete invoice record.
 *
 * @controller BrokerDeskBillingInvoiceController.at
 * @path GET /invoices/:invoiceId
 * @accessor api.functional.invoices.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(invoiceId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "GET",
    path: "/invoices/:invoiceId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}`;
}

/**
 * Create a new invoice with its charge lines.
 *
 * Accepts the invoice header together with the initial charge lines.
 * Tax rates are frozen per line from the organization's tax-rate table at
 * issuance, and header totals (subtotal, tax, grand total) are derived
 * from the lines. The invoice is created in `draft` status.
 *
 * @param body Invoice creation payload including nested charge lines.
 * @returns The created invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.create
 * @path POST /invoices
 * @accessor api.functional.invoices.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskInvoice.ICreate>;
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "POST",
    path: "/invoices",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/invoices";
}

/**
 * Update an editable invoice.
 *
 * Only invoices still in `draft` status may be revised; issued invoices
 * are immutable financial documents. Replacing the line set recomputes
 * the header totals and freezes fresh tax rates.
 *
 * @param invoiceId Target invoice identifier.
 * @param body Mutable invoice fields and replacement lines.
 * @returns The updated invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.update
 * @path PUT /invoices/:invoiceId
 * @accessor api.functional.invoices.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(invoiceId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskInvoice.IUpdate>;
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "PUT",
    path: "/invoices/:invoiceId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}`;
}

/**
 * Soft-delete an invoice.
 *
 * Hides the invoice from routine listings while preserving the financial
 * record for audit continuity.
 *
 * @param invoiceId Target invoice identifier.
 *
 * @controller BrokerDeskBillingInvoiceController.erase
 * @path DELETE /invoices/:invoiceId
 * @accessor api.functional.invoices.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(invoiceId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/invoices/:invoiceId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}`;
}

/**
 * Issue (send) a draft invoice to the client.
 *
 * Transitions the invoice from `draft` to `sent`, starting the payable
 * period shown on the printed document.
 *
 * @param invoiceId Target invoice identifier.
 * @returns The updated invoice.
 *
 * @controller BrokerDeskBillingInvoiceController.send
 * @path POST /invoices/:invoiceId/send
 * @accessor api.functional.invoices.send
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function send(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
): Promise<send.Output> {
  return PlainFetcher.fetch(connection, {
    ...send.METADATA,
    template: send.METADATA.path,
    path: send.path(invoiceId),
  });
}
export namespace send {
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "POST",
    path: "/invoices/:invoiceId/send",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/send`;
}

/**
 * Void an erroneous invoice.
 *
 * Retires the invoice without erasing audit history; voided invoices no
 * longer accept payments. Requires a recorded reason.
 *
 * @param invoiceId Target invoice identifier.
 * @param body Void reason.
 * @returns The voided invoice.
 *
 * @controller BrokerDeskBillingInvoiceController._void
 * @path POST /invoices/:invoiceId/void
 * @accessor api.functional.invoices._void
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function _void(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  body: _void.Body,
): Promise<_void.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ..._void.METADATA,
      template: _void.METADATA.path,
      path: _void.path(invoiceId),
    },
    body,
  );
}
export namespace _void {
  export type Body = Primitive<IBrokerDeskInvoice.IVoid>;
  export type Output = Primitive<IBrokerDeskInvoice>;

  export const METADATA = {
    method: "POST",
    path: "/invoices/:invoiceId/void",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}/void`;
}
