/**
 * @packageDocumentation
 * @module api.functional.notifications.unread_count
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskNotification } from "../../../../../src/api/structures/BrokerDeskSystematicNotification";

/**
 * Count unread notifications for the authenticated user.
 *
 * Lightweight badge endpoint for the staff UI.
 *
 * @returns The number of unread notifications.
 *
 * @controller BrokerDeskSystematicNotificationController.unreadCount
 * @path GET /notifications/unread-count
 * @accessor api.functional.notifications.unread_count.unreadCount
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function unreadCount(
  connection: IConnection,
): Promise<unreadCount.Output> {
  return PlainFetcher.fetch(connection, {
    ...unreadCount.METADATA,
    template: unreadCount.METADATA.path,
    path: unreadCount.path(),
  });
}
export namespace unreadCount {
  export type Output = Primitive<IBrokerDeskNotification.IUnreadCount>;

  export const METADATA = {
    method: "GET",
    path: "/notifications/unread-count",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/notifications/unread-count";
}
