/**
 * @packageDocumentation
 * @module api.functional.auth.admin.email.verify.request
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../../../../src/api/structures/BrokerDeskActorsAdmin";

/**
 * Request a single-use email verification token.
 *
 * Issues a fresh verification row rather than reviving stale ones and
 * dispatches the one-time token to the address.
 *
 * @param body Email address to verify.
 *
 * @controller BrokerDeskActorsAdminAuthController.requestEmailVerification
 * @path POST /auth/admin/email/verify/request
 * @accessor api.functional.auth.admin.email.verify.request.requestEmailVerification
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function requestEmailVerification(
  connection: IConnection,
  body: requestEmailVerification.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...requestEmailVerification.METADATA,
      template: requestEmailVerification.METADATA.path,
      path: requestEmailVerification.path(),
    },
    body,
  );
}
export namespace requestEmailVerification {
  export type Body = Primitive<IBrokerDeskAdmin.IRequestEmailVerification>;

  export const METADATA = {
    method: "POST",
    path: "/auth/admin/email/verify/request",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/admin/email/verify/request";
}
