/**
 * @packageDocumentation
 * @module api.functional.payments
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPayment } from "../../../../src/api/structures/BrokerDeskBilling";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as invoices from "./invoices/index";

/**
 * List payments received across the organization.
 *
 * Supports filtering by collection method and paid-date range for cash
 * reporting and statement reconciliation.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated payment summaries.
 *
 * @controller BrokerDeskBillingPaymentController.index
 * @path PATCH /payments
 * @accessor api.functional.payments.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskPayment.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPayment.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/payments",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/payments";
}

/**
 * Fetch a single payment record.
 *
 * @param paymentId Target payment identifier.
 * @returns The payment with its invoice context.
 *
 * @controller BrokerDeskBillingPaymentController.at
 * @path GET /payments/:paymentId
 * @accessor api.functional.payments.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  paymentId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(paymentId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskPayment>;

  export const METADATA = {
    method: "GET",
    path: "/payments/:paymentId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (paymentId: string & tags.Format<"uuid">) =>
    `/payments/${encodeURIComponent(paymentId?.toString() ?? "null")}`;
}
