/**
 * @packageDocumentation
 * @module api.functional.admin.organizations.settings
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskOrganization } from "../../../../../../src/api/structures/BrokerDeskSystematicOrganization";

/**
 * Retrieve the organization's configurable tax rate settings.
 *
 * Returns the per-province sales tax rate table (GST/HST/QST/exempt
 * handling plus broker fee taxability flags) consulted when invoice lines
 * are issued; seeded with Ontario HST 13% as the default example.
 *
 * @returns The current organization settings structure.
 *
 * @controller BrokerDeskSystematicOrganizationController.getSettings
 * @path GET /admin/organizations/settings
 * @accessor api.functional.admin.organizations.settings.getSettings
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getSettings(
  connection: IConnection,
): Promise<getSettings.Output> {
  return PlainFetcher.fetch(connection, {
    ...getSettings.METADATA,
    template: getSettings.METADATA.path,
    path: getSettings.path(),
  });
}
export namespace getSettings {
  export type Output = Primitive<IBrokerDeskOrganization.ISettings>;

  export const METADATA = {
    method: "GET",
    path: "/admin/organizations/settings",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/organizations/settings";
}
