/**
 * @packageDocumentation
 * @module api.functional.payments.invoices
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPayment } from "../../../../../src/api/structures/BrokerDeskBilling";

/**
 * Record a payment against an invoice.
 *
 * Payments are idempotent: repeating the same `idempotency_key` for the
 * same invoice collapses into a single ledger entry instead of
 * double-applying the amount. Successful application advances the
 * invoice status through `partial` to `paid` as the balance discharges.
 *
 * @param invoiceId Target invoice identifier.
 * @param body Payment creation payload with idempotency key.
 * @returns The created (or existing idempotent) payment.
 *
 * @controller BrokerDeskBillingPaymentController.create
 * @path POST /payments/invoices/:invoiceId
 * @accessor api.functional.payments.invoices.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  invoiceId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(invoiceId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskPayment.ICreate>;
  export type Output = Primitive<IBrokerDeskPayment>;

  export const METADATA = {
    method: "POST",
    path: "/payments/invoices/:invoiceId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (invoiceId: string & tags.Format<"uuid">) =>
    `/payments/invoices/${encodeURIComponent(invoiceId?.toString() ?? "null")}`;
}
