/**
 * @packageDocumentation
 * @module api.functional.documents.versions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskDocumentVersion,
  IPageIBrokerDeskDocumentVersionISummary,
} from "../../../../../src/api/structures/BrokerDeskDocument";

/**
 * List the rendition history of a document.
 *
 * Returns a paginated, chronologically ordered listing of every rendition
 * ever filed for the document, each with its own filename, MIME type, size,
 * checksum, and filing attribution. The current rendition is the highest
 * version number.
 *
 * @param documentId Identifier of the owning document.
 * @param body Pagination criteria.
 * @returns Paginated rendition summaries.
 *
 * @controller BrokerDeskDocumentVersionController.index
 * @path PATCH /documents/:documentId/versions
 * @accessor api.functional.documents.versions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(documentId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskDocumentVersion.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskDocumentVersionISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/documents/:documentId/versions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (documentId: string & tags.Format<"uuid">) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}/versions`;
}

/**
 * Read one historical rendition of a document.
 *
 * Retrieves the frozen snapshot of a specific rendition, including its
 * storage path reference and integrity checksum, so issued paperwork can be
 * presented exactly as it existed at capture time even if the source
 * template was later revised or retired.
 *
 * @param documentId Identifier of the owning document.
 * @param versionId Identifier of the target rendition.
 * @returns Rendition summary.
 *
 * @controller BrokerDeskDocumentVersionController.at
 * @path GET /documents/:documentId/versions/:versionId
 * @accessor api.functional.documents.versions.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  documentId: string & tags.Format<"uuid">,
  versionId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(documentId, versionId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskDocumentVersion.ISummary>;

  export const METADATA = {
    method: "GET",
    path: "/documents/:documentId/versions/:versionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    documentId: string & tags.Format<"uuid">,
    versionId: string & tags.Format<"uuid">,
  ) =>
    `/documents/${encodeURIComponent(documentId?.toString() ?? "null")}/versions/${encodeURIComponent(versionId?.toString() ?? "null")}`;
}
