/**
 * @packageDocumentation
 * @module api.functional.auth.client
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskClient } from "../../../../../src/api/structures/BrokerDeskActorsClient";

export * as password from "./password/index";
export * as email from "./email/index";

/**
 * Sign in as a portal client.
 *
 * Verifies the credential, gates on email verification and activation, and
 * issues a JWT pair confined to the owning brokerage.
 *
 * @param body Email and password credentials.
 * @returns The portal client with a freshly issued JWT pair.
 *
 * @controller BrokerDeskActorsClientAuthController.login
 * @path POST /auth/client/login
 * @accessor api.functional.auth.client.login
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function login(
  connection: IConnection,
  body: login.Body,
): Promise<login.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...login.METADATA,
      template: login.METADATA.path,
      path: login.path(),
    },
    body,
  );
}
export namespace login {
  export type Body = Primitive<IBrokerDeskClient.ILogin>;
  export type Output = Primitive<IBrokerDeskClient.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/client/login",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/client/login";
}

/**
 * Refresh the access token of an existing portal client session.
 *
 * @param body Refresh token previously issued by login.
 * @returns Renewed authorization payload bound to the same session.
 *
 * @controller BrokerDeskActorsClientAuthController.refresh
 * @path POST /auth/client/refresh
 * @accessor api.functional.auth.client.refresh
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refresh(
  connection: IConnection,
  body: refresh.Body,
): Promise<refresh.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...refresh.METADATA,
      template: refresh.METADATA.path,
      path: refresh.path(),
    },
    body,
  );
}
export namespace refresh {
  export type Body = Primitive<IBrokerDeskClient.IRefresh>;
  export type Output = Primitive<IBrokerDeskClient.IAuthorized>;

  export const METADATA = {
    method: "POST",
    path: "/auth/client/refresh",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/client/refresh";
}
