/**
 * @packageDocumentation
 * @module api.functional.auth.guest.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskGuestSession } from "../../../../../../src/api/structures/BrokerDeskActorsGuest";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the anonymous sessions of the authenticated guest.
 *
 * @param body Pagination criteria.
 * @returns Paginated anonymous session history of the caller.
 *
 * @controller BrokerDeskActorsGuestAuthController.index
 * @path PATCH /auth/guest/sessions
 * @accessor api.functional.auth.guest.sessions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskGuestSession.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskGuestSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/auth/guest/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/guest/sessions";
}
