/**
 * @packageDocumentation
 * @module api.functional.carriers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskCarrier,
  IPageIBrokerDeskCarrierISummary,
} from "../../../../src/api/structures/BrokerDeskCatalogueCarrier";

export * as appointments from "./appointments/index";

/**
 * List carriers with pagination, search, and filters.
 *
 * Returns the catalogue of insurance carriers visible to the authenticated
 * organization, filterable by free-text search and active flag.
 *
 * @param body Pagination and filter criteria.
 * @returns Paginated carrier summary list.
 *
 * @controller BrokerDeskCatalogueCarrierController.index
 * @path PATCH /carriers
 * @accessor api.functional.carriers.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCarrier.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskCarrierISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/carriers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/carriers";
}

/**
 * Create a new carrier catalogue entry.
 *
 * ADMIN-only operation registering a carrier with its unique code and
 * producer-support contact channels.
 *
 * @param body Carrier creation attributes.
 * @returns The newly created carrier.
 *
 * @controller BrokerDeskCatalogueCarrierController.create
 * @path POST /carriers
 * @accessor api.functional.carriers.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCarrier.ICreate>;
  export type Output = Primitive<IBrokerDeskCarrier>;

  export const METADATA = {
    method: "POST",
    path: "/carriers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/carriers";
}

/**
 * Fetch a carrier by id.
 *
 * Returns the full carrier record including its product summaries.
 *
 * @param carrierId Target carrier id.
 * @returns The carrier detail.
 *
 * @controller BrokerDeskCatalogueCarrierController.at
 * @path GET /carriers/:carrierId
 * @accessor api.functional.carriers.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(carrierId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCarrier>;

  export const METADATA = {
    method: "GET",
    path: "/carriers/:carrierId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (carrierId: string & tags.Format<"uuid">) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}`;
}

/**
 * Update a carrier's attributes.
 *
 * @param carrierId Target carrier id.
 * @param body Fields to update.
 * @returns The updated carrier.
 *
 * @controller BrokerDeskCatalogueCarrierController.update
 * @path PUT /carriers/:carrierId
 * @accessor api.functional.carriers.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(carrierId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCarrier.IUpdate>;
  export type Output = Primitive<IBrokerDeskCarrier>;

  export const METADATA = {
    method: "PUT",
    path: "/carriers/:carrierId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (carrierId: string & tags.Format<"uuid">) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}`;
}

/**
 * Delete a carrier catalogue entry.
 *
 * Historical quote lines, submissions, policies, and commissions retain
 * their carrier references for audit continuity.
 *
 * @param carrierId Target carrier id.
 *
 * @controller BrokerDeskCatalogueCarrierController.erase
 * @path DELETE /carriers/:carrierId
 * @accessor api.functional.carriers.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  carrierId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(carrierId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/carriers/:carrierId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (carrierId: string & tags.Format<"uuid">) =>
    `/carriers/${encodeURIComponent(carrierId?.toString() ?? "null")}`;
}
