/**
 * @packageDocumentation
 * @module api.functional.quotes.submissions.messages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskSubmissionMessage } from "../../../../../../src/api/structures/BrokerDeskQuoting";

/**
 * Log a conversation turn against a submission.
 *
 * The logging staff member (admin, producer, or CSR) and their session
 * are attributed from the JWT identity through the matching subtype
 * attribution table.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param submissionId Identifier of the owning submission.
 * @param body Message creation payload.
 * @returns The created conversation entry.
 *
 * @controller BrokerDeskQuotingSubmissionMessageController.create
 * @path POST /quotes/:quoteId/submissions/:submissionId/messages
 * @accessor api.functional.quotes.submissions.messages.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  submissionId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(quoteId, submissionId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskSubmissionMessage.ICreate>;
  export type Output = Primitive<IBrokerDeskSubmissionMessage>;

  export const METADATA = {
    method: "POST",
    path: "/quotes/:quoteId/submissions/:submissionId/messages",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    submissionId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions/${encodeURIComponent(submissionId?.toString() ?? "null")}/messages`;
}

/**
 * Fetch one conversation entry with its logger attribution.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param submissionId Identifier of the owning submission.
 * @param messageId Identifier of the target message.
 * @returns The full conversation entry.
 *
 * @controller BrokerDeskQuotingSubmissionMessageController.at
 * @path GET /quotes/:quoteId/submissions/:submissionId/messages/:messageId
 * @accessor api.functional.quotes.submissions.messages.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  submissionId: string & tags.Format<"uuid">,
  messageId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(quoteId, submissionId, messageId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskSubmissionMessage>;

  export const METADATA = {
    method: "GET",
    path: "/quotes/:quoteId/submissions/:submissionId/messages/:messageId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    submissionId: string & tags.Format<"uuid">,
    messageId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions/${encodeURIComponent(submissionId?.toString() ?? "null")}/messages/${encodeURIComponent(messageId?.toString() ?? "null")}`;
}

/**
 * Soft-delete an erroneous or retracted conversation entry while
 * retaining the audit trail.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param submissionId Identifier of the owning submission.
 * @param messageId Identifier of the target message.
 *
 * @controller BrokerDeskQuotingSubmissionMessageController.erase
 * @path DELETE /quotes/:quoteId/submissions/:submissionId/messages/:messageId
 * @accessor api.functional.quotes.submissions.messages.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  submissionId: string & tags.Format<"uuid">,
  messageId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(quoteId, submissionId, messageId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/quotes/:quoteId/submissions/:submissionId/messages/:messageId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    submissionId: string & tags.Format<"uuid">,
    messageId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/submissions/${encodeURIComponent(submissionId?.toString() ?? "null")}/messages/${encodeURIComponent(messageId?.toString() ?? "null")}`;
}
