/**
 * @packageDocumentation
 * @module api.functional.commissions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskCommission } from "../../../../src/api/structures/BrokerDeskBilling";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as me from "./me/index";

/**
 * List commissions for the organization.
 *
 * Filter by producer, carrier, policy, lifecycle status, and statement
 * period. Producers see only their own commissions; admins see all.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated commission summaries.
 *
 * @controller BrokerDeskBillingCommissionController.index
 * @path PATCH /commissions
 * @accessor api.functional.commissions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCommission.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskCommission.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/commissions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/commissions";
}

/**
 * Fetch a single commission record.
 *
 * @param commissionId Target commission identifier.
 * @returns The complete commission record.
 *
 * @controller BrokerDeskBillingCommissionController.at
 * @path GET /commissions/:commissionId
 * @accessor api.functional.commissions.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  commissionId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(commissionId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCommission>;

  export const METADATA = {
    method: "GET",
    path: "/commissions/:commissionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (commissionId: string & tags.Format<"uuid">) =>
    `/commissions/${encodeURIComponent(commissionId?.toString() ?? "null")}`;
}

/**
 * Manually record a commission entry.
 *
 * Used for adjustments and book-roll policies where no automatic
 * generation occurred; rates and amounts are frozen as point-in-time
 * financial facts.
 *
 * @param body Commission creation payload.
 * @returns The created commission.
 *
 * @controller BrokerDeskBillingCommissionController.create
 * @path POST /commissions
 * @accessor api.functional.commissions.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCommission.ICreate>;
  export type Output = Primitive<IBrokerDeskCommission>;

  export const METADATA = {
    method: "POST",
    path: "/commissions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/commissions";
}

/**
 * Update a commission entry.
 *
 * Corrections to rates, amounts, status, or statement period; settled
 * commissions attached to a paid statement are immutable.
 *
 * @param commissionId Target commission identifier.
 * @param body Mutable commission fields.
 * @returns The updated commission.
 *
 * @controller BrokerDeskBillingCommissionController.update
 * @path PUT /commissions/:commissionId
 * @accessor api.functional.commissions.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  commissionId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(commissionId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCommission.IUpdate>;
  export type Output = Primitive<IBrokerDeskCommission>;

  export const METADATA = {
    method: "PUT",
    path: "/commissions/:commissionId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (commissionId: string & tags.Format<"uuid">) =>
    `/commissions/${encodeURIComponent(commissionId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a commission from the active ledger.
 *
 * Preserves financial history for audit and reporting.
 *
 * @param commissionId Target commission identifier.
 *
 * @controller BrokerDeskBillingCommissionController.erase
 * @path DELETE /commissions/:commissionId
 * @accessor api.functional.commissions.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  commissionId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(commissionId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/commissions/:commissionId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (commissionId: string & tags.Format<"uuid">) =>
    `/commissions/${encodeURIComponent(commissionId?.toString() ?? "null")}`;
}

/**
 * Invert a commission with its policy and producer context.
 *
 * Returns the commission together with its parent policy and producer
 * summaries for detail views.
 *
 * @param commissionId Target commission identifier.
 * @returns The commission with parent context.
 *
 * @controller BrokerDeskBillingCommissionController.invert
 * @path GET /commissions/:commissionId/invert
 * @accessor api.functional.commissions.invert
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function invert(
  connection: IConnection,
  commissionId: string & tags.Format<"uuid">,
): Promise<invert.Output> {
  return PlainFetcher.fetch(connection, {
    ...invert.METADATA,
    template: invert.METADATA.path,
    path: invert.path(commissionId),
  });
}
export namespace invert {
  export type Output = Primitive<IBrokerDeskCommission.IInvert>;

  export const METADATA = {
    method: "GET",
    path: "/commissions/:commissionId/invert",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (commissionId: string & tags.Format<"uuid">) =>
    `/commissions/${encodeURIComponent(commissionId?.toString() ?? "null")}/invert`;
}
