/**
 * @packageDocumentation
 * @module api.functional.clients.documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskClientDocument } from "../../../../../src/api/structures/BrokerDeskCrmClient";

/**
 * List documents attached to a client.
 *
 * @param clientId Primary key of the target client.
 * @returns Document metadata records.
 *
 * @controller BrokerDeskCrmClientController.documents
 * @path GET /clients/:clientId/documents
 * @accessor api.functional.clients.documents.documents
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function documents(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<documents.Output> {
  return PlainFetcher.fetch(connection, {
    ...documents.METADATA,
    template: documents.METADATA.path,
    path: documents.path(clientId),
  });
}
export namespace documents {
  export type Output = Primitive<Array<IBrokerDeskClientDocument>>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/documents",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/documents`;
}

/**
 * Upload (register) a document against a client.
 *
 * Stores metadata plus the storage key of the uploaded content and records
 * the uploading staff member from the JWT.
 *
 * @param clientId Primary key of the target client.
 * @param body Document registration payload.
 * @returns The created document metadata.
 *
 * @controller BrokerDeskCrmClientController.createDocument
 * @path POST /clients/:clientId/documents
 * @accessor api.functional.clients.documents.createDocument
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createDocument(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: createDocument.Body,
): Promise<createDocument.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createDocument.METADATA,
      template: createDocument.METADATA.path,
      path: createDocument.path(clientId),
    },
    body,
  );
}
export namespace createDocument {
  export type Body = Primitive<{
    kind: string;
    filename: string;
    mime_type: string;
    size: number;
    storage_path: string;
    checksum?: string | null;
  }>;
  export type Output = Primitive<IBrokerDeskClientDocument>;

  export const METADATA = {
    method: "POST",
    path: "/clients/:clientId/documents",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/documents`;
}
