/**
 * @packageDocumentation
 * @module api.functional.admin.audit_logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAuditLog } from "../../../../../src/api/structures/BrokerDeskSystematicAuditLog";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List audit log entries.
 *
 * Filters by actor type, action, entity type, optional target id, and a
 * date range; supports pagination and ordering by occurred_at. Used by the
 * administrator to investigate changes within the organization.
 *
 * @param body Search and pagination criteria.
 * @returns Page of audit log summaries.
 *
 * @controller BrokerDeskSystematicAuditLogController.index
 * @path PATCH /admin/audit-logs
 * @accessor api.functional.admin.audit_logs.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskAuditLog.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskAuditLog.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/audit-logs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/audit-logs";
}

/**
 * Retrieve a single audit log entry with its full detail.
 *
 * @param auditLogId Target audit log key.
 * @returns The full audit record.
 *
 * @controller BrokerDeskSystematicAuditLogController.at
 * @path GET /admin/audit-logs/:auditLogId
 * @accessor api.functional.admin.audit_logs.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  auditLogId: string,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(auditLogId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskAuditLog>;

  export const METADATA = {
    method: "GET",
    path: "/admin/audit-logs/:auditLogId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (auditLogId: string) =>
    `/admin/audit-logs/${encodeURIComponent(auditLogId?.toString() ?? "null")}`;
}
