/**
 * @packageDocumentation
 * @module api.functional.notifications
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskNotification } from "../../../../src/api/structures/BrokerDeskSystematicNotification";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as read from "./read/index";
export * as unread_count from "./unread_count/index";

/**
 * List the authenticated user's notifications.
 *
 * Filters by type and read state; supports pagination and ordering.
 *
 * @param body Search and pagination criteria.
 * @returns Page of notification summaries.
 *
 * @controller BrokerDeskSystematicNotificationController.index
 * @path PATCH /notifications
 * @accessor api.functional.notifications.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskNotification.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskNotification.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/notifications",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/notifications";
}

/**
 * Retrieve one of the authenticated user's notifications.
 *
 * @param notificationId Target notification key.
 * @returns The full notification record.
 *
 * @controller BrokerDeskSystematicNotificationController.at
 * @path GET /notifications/:notificationId
 * @accessor api.functional.notifications.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  notificationId: string,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(notificationId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskNotification>;

  export const METADATA = {
    method: "GET",
    path: "/notifications/:notificationId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (notificationId: string) =>
    `/notifications/${encodeURIComponent(notificationId?.toString() ?? "null")}`;
}
