/**
 * @packageDocumentation
 * @module api.functional.auth.admin.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdmin } from "../../../../../../src/api/structures/BrokerDeskActorsAdmin";

/**
 * Retrieve the profile of the authenticated administrator.
 *
 * Resolved from the JWT subject; no path parameter is accepted for
 * self-access.
 *
 * @returns The administrator record of the caller.
 *
 * @controller BrokerDeskActorsAdminAuthController.me
 * @path GET /auth/admin/me
 * @accessor api.functional.auth.admin.me.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = Primitive<IBrokerDeskAdmin>;

  export const METADATA = {
    method: "GET",
    path: "/auth/admin/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/admin/me";
}

/**
 * Update the profile of the authenticated administrator.
 *
 * @param body Mutable profile fields.
 * @returns The refreshed administrator record.
 *
 * @controller BrokerDeskActorsAdminAuthController.update
 * @path PUT /auth/admin/me
 * @accessor api.functional.auth.admin.me.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskAdmin.IUpdate>;
  export type Output = Primitive<IBrokerDeskAdmin>;

  export const METADATA = {
    method: "PUT",
    path: "/auth/admin/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/admin/me";
}
