/**
 * @packageDocumentation
 * @module api.functional.commissions.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskCommission } from "../../../../../src/api/structures/BrokerDeskBilling";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List the requesting producer's own commissions.
 *
 * Self-only visibility path for producers under the actor prefix.
 *
 * @param body Search and pagination criteria scoped to self.
 * @returns Paginated commission summaries for the current producer.
 *
 * @controller BrokerDeskBillingCommissionController.myIndex
 * @path PATCH /commissions/me
 * @accessor api.functional.commissions.me.myIndex
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function myIndex(
  connection: IConnection,
  body: myIndex.Body,
): Promise<myIndex.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...myIndex.METADATA,
      template: myIndex.METADATA.path,
      path: myIndex.path(),
    },
    body,
  );
}
export namespace myIndex {
  export type Body = Primitive<IBrokerDeskCommission.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskCommission.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/commissions/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/commissions/me";
}
