/**
 * @packageDocumentation
 * @module api.functional.admin.producers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskProducer } from "../../../../../src/api/structures/BrokerDeskActorsProducer";
import type { IPage } from "../../../../../src/api/structures/IPage";

export * as licences from "./licences/index";

/**
 * List producer accounts of the caller's organization.
 *
 * @param body Search, filter, and pagination criteria.
 * @returns Paginated producer summaries.
 *
 * @controller BrokerDeskActorsAdminProducersController.index
 * @path PATCH /admin/producers
 * @accessor api.functional.admin.producers.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskProducer.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskProducer.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/producers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/producers";
}

/**
 * Invite a new producer into the caller's organization.
 *
 * The invited account reaches first sign-in through the email verification
 * setup path.
 *
 * @param body Invitation body (email, display name, activation standing).
 * @returns The newly provisioned producer.
 *
 * @controller BrokerDeskActorsAdminProducersController.create
 * @path POST /admin/producers
 * @accessor api.functional.admin.producers.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskProducer.ICreate>;
  export type Output = Primitive<IBrokerDeskProducer>;

  export const METADATA = {
    method: "POST",
    path: "/admin/producers",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/producers";
}

/**
 * Retrieve one producer account in detail.
 *
 * @param producerId Target producer identifier.
 * @returns The producer record with licences and sessions.
 *
 * @controller BrokerDeskActorsAdminProducersController.at
 * @path GET /admin/producers/:producerId
 * @accessor api.functional.admin.producers.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(producerId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskProducer>;

  export const METADATA = {
    method: "GET",
    path: "/admin/producers/:producerId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (producerId: string & tags.Format<"uuid">) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}`;
}

/**
 * Update a producer account.
 *
 * Deactivation terminates the producer's open sessions immediately.
 *
 * @param producerId Target producer identifier.
 * @param body Mutable account fields.
 * @returns The updated producer record.
 *
 * @controller BrokerDeskActorsAdminProducersController.update
 * @path PUT /admin/producers/:producerId
 * @accessor api.functional.admin.producers.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(producerId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskProducer.IUpdate>;
  export type Output = Primitive<IBrokerDeskProducer>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/producers/:producerId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (producerId: string & tags.Format<"uuid">) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a producer account.
 *
 * The row is retained so every owned record stays attributable while the
 * account disappears from listings and assignment choices.
 *
 * @param producerId Target producer identifier.
 *
 * @controller BrokerDeskActorsAdminProducersController.erase
 * @path DELETE /admin/producers/:producerId
 * @accessor api.functional.admin.producers.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  producerId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(producerId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/admin/producers/:producerId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (producerId: string & tags.Format<"uuid">) =>
    `/admin/producers/${encodeURIComponent(producerId?.toString() ?? "null")}`;
}
