/**
 * @packageDocumentation
 * @module api.functional.admin.csrs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskCsr } from "../../../../../src/api/structures/BrokerDeskActorsCsr";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List CSR accounts of the caller's organization.
 *
 * @param body Search, filter, and pagination criteria.
 * @returns Paginated CSR summaries.
 *
 * @controller BrokerDeskActorsAdminCsrsController.index
 * @path PATCH /admin/csrs
 * @accessor api.functional.admin.csrs.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCsr.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskCsr.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/admin/csrs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/csrs";
}

/**
 * Invite a new CSR into the caller's organization.
 *
 * The invited account starts without a password and reaches first sign-in
 * through the one-time setup path that also verifies the email address.
 *
 * @param body Invitation body (email, display name, activation standing).
 * @returns The newly provisioned CSR.
 *
 * @controller BrokerDeskActorsAdminCsrsController.create
 * @path POST /admin/csrs
 * @accessor api.functional.admin.csrs.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCsr.ICreate>;
  export type Output = Primitive<IBrokerDeskCsr>;

  export const METADATA = {
    method: "POST",
    path: "/admin/csrs",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/admin/csrs";
}

/**
 * Retrieve one CSR account in detail.
 *
 * @param csrId Target CSR identifier.
 * @returns The CSR record with sessions.
 *
 * @controller BrokerDeskActorsAdminCsrsController.at
 * @path GET /admin/csrs/:csrId
 * @accessor api.functional.admin.csrs.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  csrId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(csrId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskCsr>;

  export const METADATA = {
    method: "GET",
    path: "/admin/csrs/:csrId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (csrId: string & tags.Format<"uuid">) =>
    `/admin/csrs/${encodeURIComponent(csrId?.toString() ?? "null")}`;
}

/**
 * Update a CSR account.
 *
 * Deactivation terminates the representative's open sessions immediately.
 *
 * @param csrId Target CSR identifier.
 * @param body Mutable account fields.
 * @returns The updated CSR record.
 *
 * @controller BrokerDeskActorsAdminCsrsController.update
 * @path PUT /admin/csrs/:csrId
 * @accessor api.functional.admin.csrs.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  csrId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(csrId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCsr.IUpdate>;
  export type Output = Primitive<IBrokerDeskCsr>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/csrs/:csrId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (csrId: string & tags.Format<"uuid">) =>
    `/admin/csrs/${encodeURIComponent(csrId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a CSR account.
 *
 * Staff accounts are never permanently deleted; removal-like effects are
 * expressed through the activation standing instead.
 *
 * @param csrId Target CSR identifier.
 *
 * @controller BrokerDeskActorsAdminCsrsController.erase
 * @path DELETE /admin/csrs/:csrId
 * @accessor api.functional.admin.csrs.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  csrId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(csrId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/admin/csrs/:csrId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (csrId: string & tags.Format<"uuid">) =>
    `/admin/csrs/${encodeURIComponent(csrId?.toString() ?? "null")}`;
}
