/**
 * @packageDocumentation
 * @module api.functional.policies.renewals
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPolicyRenewal } from "../../../../../src/api/structures/BrokerDeskPolicy";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List renewal offers with filtering and pagination.
 *
 * @param body Search criteria including status and prior/next policy filters.
 * @returns Paginated renewal summaries.
 *
 * @controller BrokerDeskPolicyRenewalController.index
 * @path PATCH /policies/renewals
 * @accessor api.functional.policies.renewals.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskPolicyRenewal.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPolicyRenewal.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/policies/renewals",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/policies/renewals";
}

/**
 * Retrieve a single renewal offer.
 *
 * @param renewalId Target renewal id.
 * @returns The renewal record.
 *
 * @controller BrokerDeskPolicyRenewalController.at
 * @path GET /policies/renewals/:renewalId
 * @accessor api.functional.policies.renewals.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  renewalId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(renewalId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskPolicyRenewal>;

  export const METADATA = {
    method: "GET",
    path: "/policies/renewals/:renewalId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (renewalId: string & tags.Format<"uuid">) =>
    `/policies/renewals/${encodeURIComponent(renewalId?.toString() ?? "null")}`;
}

/**
 * Extend renewal terms to the client, moving the record from scheduled to
 * offered and stamping the offered premium and offer timestamp.
 *
 * @param renewalId Target renewal id.
 * @param body Offer parameters.
 * @returns The updated renewal record.
 *
 * @controller BrokerDeskPolicyRenewalController.offer
 * @path POST /policies/renewals/:renewalId/offer
 * @accessor api.functional.policies.renewals.offer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function offer(
  connection: IConnection,
  renewalId: string & tags.Format<"uuid">,
  body: offer.Body,
): Promise<offer.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...offer.METADATA,
      template: offer.METADATA.path,
      path: offer.path(renewalId),
    },
    body,
  );
}
export namespace offer {
  export type Body = Primitive<IBrokerDeskPolicyRenewal.IOffer>;
  export type Output = Primitive<IBrokerDeskPolicyRenewal>;

  export const METADATA = {
    method: "POST",
    path: "/policies/renewals/:renewalId/offer",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (renewalId: string & tags.Format<"uuid">) =>
    `/policies/renewals/${encodeURIComponent(renewalId?.toString() ?? "null")}/offer`;
}

/**
 * Resolve a renewal into a terminal state; accepted or rewritten decisions
 * generate the next-term policy transactionally.
 *
 * @param renewalId Target renewal id.
 * @param body Decision payload.
 * @returns The updated renewal record including the successor policy when generated.
 *
 * @controller BrokerDeskPolicyRenewalController.decide
 * @path POST /policies/renewals/:renewalId/decide
 * @accessor api.functional.policies.renewals.decide
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function decide(
  connection: IConnection,
  renewalId: string & tags.Format<"uuid">,
  body: decide.Body,
): Promise<decide.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...decide.METADATA,
      template: decide.METADATA.path,
      path: decide.path(renewalId),
    },
    body,
  );
}
export namespace decide {
  export type Body = Primitive<IBrokerDeskPolicyRenewal.IDecide>;
  export type Output = Primitive<IBrokerDeskPolicyRenewal>;

  export const METADATA = {
    method: "POST",
    path: "/policies/renewals/:renewalId/decide",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (renewalId: string & tags.Format<"uuid">) =>
    `/policies/renewals/${encodeURIComponent(renewalId?.toString() ?? "null")}/decide`;
}
