/**
 * @packageDocumentation
 * @module api.functional.products.coverage_items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskCoverageItem,
  IPageIBrokerDeskCoverageItemISummary,
} from "../../../../../src/api/structures/BrokerDeskCatalogueProduct";

/**
 * List coverage items of a product with pagination and filters.
 *
 * @param productId Parent product id.
 * @param body Pagination and filter criteria.
 * @returns Paginated coverage-item summary list.
 *
 * @controller BrokerDeskCatalogueCoverageItemController.index
 * @path PATCH /products/:productId/coverage-items
 * @accessor api.functional.products.coverage_items.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(productId),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskCoverageItem.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskCoverageItemISummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/products/:productId/coverage-items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/coverage-items`;
}

/**
 * Create a coverage item under a product.
 *
 * ADMIN-only operation; the code must be unique within the parent product.
 *
 * @param productId Parent product id.
 * @param body Coverage-item creation attributes.
 * @returns The newly created coverage item.
 *
 * @controller BrokerDeskCatalogueCoverageItemController.create
 * @path POST /products/:productId/coverage-items
 * @accessor api.functional.products.coverage_items.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(productId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskCoverageItem.ICreate>;
  export type Output = Primitive<IBrokerDeskCoverageItem>;

  export const METADATA = {
    method: "POST",
    path: "/products/:productId/coverage-items",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (productId: string & tags.Format<"uuid">) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/coverage-items`;
}

/**
 * Fetch a coverage item with its parent product context.
 *
 * @param productId Parent product id.
 * @param coverageItemId Target coverage-item id.
 * @returns The coverage item with parent context.
 *
 * @controller BrokerDeskCatalogueCoverageItemController.invert
 * @path GET /products/:productId/coverage-items/:coverageItemId/invert
 * @accessor api.functional.products.coverage_items.invert
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function invert(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  coverageItemId: string & tags.Format<"uuid">,
): Promise<invert.Output> {
  return PlainFetcher.fetch(connection, {
    ...invert.METADATA,
    template: invert.METADATA.path,
    path: invert.path(productId, coverageItemId),
  });
}
export namespace invert {
  export type Output = Primitive<IBrokerDeskCoverageItem.IInvert>;

  export const METADATA = {
    method: "GET",
    path: "/products/:productId/coverage-items/:coverageItemId/invert",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    productId: string & tags.Format<"uuid">,
    coverageItemId: string & tags.Format<"uuid">,
  ) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/coverage-items/${encodeURIComponent(coverageItemId?.toString() ?? "null")}/invert`;
}

/**
 * Update a coverage item.
 *
 * Edits affect only future selections; issued quote lines and policy
 * coverage schedules retain their frozen copies.
 *
 * @param productId Parent product id.
 * @param coverageItemId Target coverage-item id.
 * @param body Fields to update.
 * @returns The updated coverage item.
 *
 * @controller BrokerDeskCatalogueCoverageItemController.update
 * @path PUT /products/:productId/coverage-items/:coverageItemId
 * @accessor api.functional.products.coverage_items.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  coverageItemId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(productId, coverageItemId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskCoverageItem.IUpdate>;
  export type Output = Primitive<IBrokerDeskCoverageItem>;

  export const METADATA = {
    method: "PUT",
    path: "/products/:productId/coverage-items/:coverageItemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    productId: string & tags.Format<"uuid">,
    coverageItemId: string & tags.Format<"uuid">,
  ) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/coverage-items/${encodeURIComponent(coverageItemId?.toString() ?? "null")}`;
}

/**
 * Delete a coverage item catalogue entry.
 *
 * @param productId Parent product id.
 * @param coverageItemId Target coverage-item id.
 *
 * @controller BrokerDeskCatalogueCoverageItemController.erase
 * @path DELETE /products/:productId/coverage-items/:coverageItemId
 * @accessor api.functional.products.coverage_items.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  productId: string & tags.Format<"uuid">,
  coverageItemId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(productId, coverageItemId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/products/:productId/coverage-items/:coverageItemId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    productId: string & tags.Format<"uuid">,
    coverageItemId: string & tags.Format<"uuid">,
  ) =>
    `/products/${encodeURIComponent(productId?.toString() ?? "null")}/coverage-items/${encodeURIComponent(coverageItemId?.toString() ?? "null")}`;
}
