/**
 * @packageDocumentation
 * @module api.functional.policies
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskPolicy,
  IBrokerDeskPolicyCancellation,
  IBrokerDeskPolicyReinstatement,
} from "../../../../src/api/structures/BrokerDeskPolicy";
import type { IPage } from "../../../../src/api/structures/IPage";

export * as documents from "./documents/index";
export * as endorsements from "./endorsements/index";
export * as renewal_candidates from "./renewal_candidates/index";
export * as renewals from "./renewals/index";
export * as coverages from "./coverages/index";
export * as cancellations from "./cancellations/index";

/**
 * List policies with filtering, sorting, and pagination.
 *
 * Filters include client, carrier, product, producer, status, province of
 * risk, and a term-end date range supporting the renewal candidate scan.
 *
 * @param body Search and pagination criteria.
 * @returns Paginated policy summaries.
 *
 * @controller BrokerDeskPolicyPolicyController.index
 * @path PATCH /policies
 * @accessor api.functional.policies.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskPolicy.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskPolicy.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/policies",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/policies";
}

/**
 * Retrieve a single policy by id with full composition.
 *
 * @param policyId Target policy id.
 * @returns The policy including coverages, endorsements, cancellations, renewals.
 *
 * @controller BrokerDeskPolicyPolicyController.at
 * @path GET /policies/:policyId
 * @accessor api.functional.policies.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(policyId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskPolicy>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}`;
}

/**
 * Manually create a book-roll policy without a quoting origin.
 *
 * Coverage schedule lines may be supplied inline; the policy is created in
 * the active status with the supplied term and financial figures.
 *
 * @param body Policy creation payload.
 * @returns The newly created policy.
 *
 * @controller BrokerDeskPolicyPolicyController.create
 * @path POST /policies
 * @accessor api.functional.policies.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskPolicy.ICreate>;
  export type Output = Primitive<IBrokerDeskPolicy>;

  export const METADATA = {
    method: "POST",
    path: "/policies",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/policies";
}

/**
 * Update mutable policy attributes such as term, financials, and producer.
 *
 * @param policyId Target policy id.
 * @param body Fields to update; all optional.
 * @returns The updated policy.
 *
 * @controller BrokerDeskPolicyPolicyController.update
 * @path PUT /policies/:policyId
 * @accessor api.functional.policies.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(policyId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskPolicy.IUpdate>;
  export type Output = Primitive<IBrokerDeskPolicy>;

  export const METADATA = {
    method: "PUT",
    path: "/policies/:policyId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a policy, preserving history for audit and commission review.
 *
 * @param policyId Target policy id.
 *
 * @controller BrokerDeskPolicyPolicyController.erase
 * @path DELETE /policies/:policyId
 * @accessor api.functional.policies.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(policyId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/policies/:policyId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}`;
}

/**
 * Record the carrier-assigned policy number against an issued contract.
 *
 * @param policyId Target policy id.
 * @param body Carrier policy number payload.
 * @returns The updated policy.
 *
 * @controller BrokerDeskPolicyPolicyController.issue
 * @path POST /policies/:policyId/issue
 * @accessor api.functional.policies.issue
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function issue(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: issue.Body,
): Promise<issue.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...issue.METADATA,
      template: issue.METADATA.path,
      path: issue.path(policyId),
    },
    body,
  );
}
export namespace issue {
  export type Body = Primitive<IBrokerDeskPolicy.IIssue>;
  export type Output = Primitive<IBrokerDeskPolicy>;

  export const METADATA = {
    method: "POST",
    path: "/policies/:policyId/issue",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/issue`;
}

/**
 * Cancel a policy before its term end, creating a cancellation record and
 * transitioning the policy status to pending_cancel.
 *
 * @param policyId Target policy id.
 * @param body Cancellation parameters.
 * @returns The updated policy and the created cancellation.
 *
 * @controller BrokerDeskPolicyPolicyController.cancel
 * @path POST /policies/:policyId/cancel
 * @accessor api.functional.policies.cancel
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancel(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: cancel.Body,
): Promise<cancel.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...cancel.METADATA,
      template: cancel.METADATA.path,
      path: cancel.path(policyId),
    },
    body,
  );
}
export namespace cancel {
  export type Body = Primitive<IBrokerDeskPolicyCancellation.ICreate>;
  export type Output = Primitive<IBrokerDeskPolicy.ICancellationResult>;

  export const METADATA = {
    method: "POST",
    path: "/policies/:policyId/cancel",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/cancel`;
}

/**
 * Reinstate a cancelled policy, reversing a prior termination record.
 *
 * @param policyId Target policy id.
 * @param body Reinstatement parameters.
 * @returns The updated policy and the created reinstatement.
 *
 * @controller BrokerDeskPolicyPolicyController.reinstate
 * @path POST /policies/:policyId/reinstate
 * @accessor api.functional.policies.reinstate
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function reinstate(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  body: reinstate.Body,
): Promise<reinstate.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...reinstate.METADATA,
      template: reinstate.METADATA.path,
      path: reinstate.path(policyId),
    },
    body,
  );
}
export namespace reinstate {
  export type Body = Primitive<IBrokerDeskPolicyReinstatement.ICreate>;
  export type Output = Primitive<IBrokerDeskPolicy.IReinstatementResult>;

  export const METADATA = {
    method: "POST",
    path: "/policies/:policyId/reinstate",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/reinstate`;
}
