/**
 * @packageDocumentation
 * @module api.functional.auth.admin.sessions
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskAdminSession } from "../../../../../../src/api/structures/BrokerDeskActorsAdmin";
import type { IPage } from "../../../../../../src/api/structures/IPage";

/**
 * List the sign-in sessions of the authenticated administrator.
 *
 * The session history is the security audit surface of the account; rows
 * are ordered newest first and every entry carries its request context.
 *
 * @param body Pagination criteria.
 * @returns Paginated session history of the caller.
 *
 * @controller BrokerDeskActorsAdminAuthController.index
 * @path PATCH /auth/admin/sessions
 * @accessor api.functional.auth.admin.sessions.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskAdminSession.IRequest>;
  export type Output = Primitive<IPage<IBrokerDeskAdminSession.ISummary>>;

  export const METADATA = {
    method: "PATCH",
    path: "/auth/admin/sessions",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/auth/admin/sessions";
}
