/**
 * @packageDocumentation
 * @module api.functional.admin.organizations.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskOrganization } from "../../../../../../src/api/structures/BrokerDeskSystematicOrganization";

/**
 * Retrieve the authenticated administrator's brokerage organization.
 *
 * Returns the complete tenant profile: legal identity, contact channel,
 * CRA tax registration, principal office address, fixed CAD currency, and
 * the parsed organization settings holding the provincial tax rate table
 * seeded with Ontario HST 13%.
 *
 * @returns The full organization profile of the JWT tenant.
 *
 * @controller BrokerDeskSystematicOrganizationController.at
 * @path GET /admin/organizations/me
 * @accessor api.functional.admin.organizations.me.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(connection: IConnection): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskOrganization>;

  export const METADATA = {
    method: "GET",
    path: "/admin/organizations/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/organizations/me";
}

/**
 * Update the authenticated administrator's brokerage organization profile.
 *
 * Accepts partial modifications of the legal identity, contact channel,
 * principal office address, and operating province. The currency is fixed
 * to CAD and never editable; the tax rate settings are maintained through
 * the dedicated settings endpoint.
 *
 * @param body Profile fields to update; omitted fields keep their current values.
 * @returns The refreshed organization profile.
 *
 * @controller BrokerDeskSystematicOrganizationController.update
 * @path PUT /admin/organizations/me
 * @accessor api.functional.admin.organizations.me.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskOrganization.IUpdate>;
  export type Output = Primitive<IBrokerDeskOrganization>;

  export const METADATA = {
    method: "PUT",
    path: "/admin/organizations/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/admin/organizations/me";
}
