/**
 * @packageDocumentation
 * @module api.functional.dashboard.revenue
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskRevenueDashboard } from "../../../../../src/api/structures/BrokerDeskBilling";

/**
 * Revenue dashboard summary for the organization or a single producer.
 *
 * Aggregates commission due, bound premium MTD/YTD, the quote pipeline
 * by status, and accounts-receivable totals by invoice status. When a
 * producer filter is supplied the figures scope to that producer's book
 * of business; otherwise the summary covers the whole organization.
 *
 * @param body Optional producer scope filter.
 * @returns Revenue and receivable dashboard aggregates.
 *
 * @controller BrokerDeskBillingDashboardController.summary
 * @path POST /dashboard/revenue/summary
 * @accessor api.functional.dashboard.revenue.summary
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function summary(
  connection: IConnection,
  body: summary.Body,
): Promise<summary.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...summary.METADATA,
      template: summary.METADATA.path,
      path: summary.path(),
    },
    body,
  );
}
export namespace summary {
  export type Body = Primitive<IBrokerDeskRevenueDashboard.IRequest>;
  export type Output = Primitive<IBrokerDeskRevenueDashboard>;

  export const METADATA = {
    method: "POST",
    path: "/dashboard/revenue/summary",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/dashboard/revenue/summary";
}
