/**
 * @packageDocumentation
 * @module api.functional.notifications.read
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskNotification } from "../../../../../src/api/structures/BrokerDeskSystematicNotification";

/**
 * Mark a notification as read.
 *
 * Idempotent: marking an already-read notification succeeds without
 * changing anything.
 *
 * @param notificationId Target notification key.
 * @returns The refreshed notification record.
 *
 * @controller BrokerDeskSystematicNotificationController.markRead
 * @path PATCH /notifications/:notificationId/read
 * @accessor api.functional.notifications.read.markRead
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function markRead(
  connection: IConnection,
  notificationId: string,
): Promise<markRead.Output> {
  return PlainFetcher.fetch(connection, {
    ...markRead.METADATA,
    template: markRead.METADATA.path,
    path: markRead.path(notificationId),
  });
}
export namespace markRead {
  export type Output = Primitive<IBrokerDeskNotification>;

  export const METADATA = {
    method: "PATCH",
    path: "/notifications/:notificationId/read",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (notificationId: string) =>
    `/notifications/${encodeURIComponent(notificationId?.toString() ?? "null")}/read`;
}
