/**
 * @packageDocumentation
 * @module api.functional.admin.organizations
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as me from "./me/index";
export * as settings from "./settings/index";
