/**
 * @packageDocumentation
 * @module api.functional.clients.contacts
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskClientContact } from "../../../../../src/api/structures/BrokerDeskCrmClient";

/**
 * List the contact directory of a client.
 *
 * Returns non-deleted contacts ordered with the primary contact first.
 *
 * @param clientId Primary key of the parent client.
 * @returns The client's contacts.
 *
 * @controller BrokerDeskCrmClientContactController.index
 * @path GET /clients/:clientId/contacts
 * @accessor api.functional.clients.contacts.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(clientId),
  });
}
export namespace index {
  export type Output = Primitive<Array<IBrokerDeskClientContact>>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/contacts",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/contacts`;
}

/**
 * Read one contact of a client.
 *
 * @param clientId Primary key of the parent client.
 * @param contactId Primary key of the contact.
 * @returns The contact detail.
 *
 * @controller BrokerDeskCrmClientContactController.at
 * @path GET /clients/:clientId/contacts/:contactId
 * @accessor api.functional.clients.contacts.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  contactId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(clientId, contactId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskClientContact>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/contacts/:contactId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    contactId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/contacts/${encodeURIComponent(contactId?.toString() ?? "null")}`;
}

/**
 * Create a contact under a business client.
 *
 * When marked primary, any previous primary designation on the client is
 * cleared so exactly one primary contact remains.
 *
 * @param clientId Primary key of the parent client.
 * @param body Contact creation payload.
 * @returns The created contact.
 *
 * @controller BrokerDeskCrmClientContactController.create
 * @path POST /clients/:clientId/contacts
 * @accessor api.functional.clients.contacts.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(clientId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskClientContact.ICreate>;
  export type Output = Primitive<IBrokerDeskClientContact>;

  export const METADATA = {
    method: "POST",
    path: "/clients/:clientId/contacts",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/contacts`;
}

/**
 * Update a contact's details.
 *
 * @param clientId Primary key of the parent client.
 * @param contactId Primary key of the contact.
 * @param body Fields to update, all optional.
 * @returns The updated contact.
 *
 * @controller BrokerDeskCrmClientContactController.update
 * @path PUT /clients/:clientId/contacts/:contactId
 * @accessor api.functional.clients.contacts.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  contactId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(clientId, contactId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskClientContact.IUpdate>;
  export type Output = Primitive<IBrokerDeskClientContact>;

  export const METADATA = {
    method: "PUT",
    path: "/clients/:clientId/contacts/:contactId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    contactId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/contacts/${encodeURIComponent(contactId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a contact, keeping historical activities attributable.
 *
 * @param clientId Primary key of the parent client.
 * @param contactId Primary key of the contact.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmClientContactController.erase
 * @path DELETE /clients/:clientId/contacts/:contactId
 * @accessor api.functional.clients.contacts.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  contactId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(clientId, contactId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/clients/:clientId/contacts/:contactId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    contactId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/contacts/${encodeURIComponent(contactId?.toString() ?? "null")}`;
}
