/**
 * @packageDocumentation
 * @module api.functional.clients
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type {
  IBrokerDeskClient,
  IPageIBrokerDeskClientSummary,
} from "../../../../src/api/structures/BrokerDeskCrmClient";

export * as me from "./me/index";
export * as activities from "./activities/index";
export * as addresses from "./addresses/index";
export * as contacts from "./contacts/index";
export * as tags from "./tags/index";
export * as documents from "./documents/index";

/**
 * List and filter clients of the acting organization.
 *
 * Supports pagination, free-text name search, and filters by status,
 * producer, province, client type, and tags. Results are paginated client
 * summaries without heavyweight has-many aggregates.
 *
 * @param body Search and filter criteria.
 * @returns Paginated client summaries.
 *
 * @controller BrokerDeskCrmClientController.index
 * @path PATCH /clients
 * @accessor api.functional.clients.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  body: index.Body,
): Promise<index.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...index.METADATA,
      template: index.METADATA.path,
      path: index.path(),
    },
    body,
  );
}
export namespace index {
  export type Body = Primitive<IBrokerDeskClient.IRequest>;
  export type Output = Primitive<IPageIBrokerDeskClientSummary>;

  export const METADATA = {
    method: "PATCH",
    path: "/clients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/clients";
}

/**
 * Read one client in full detail.
 *
 * Returns every public column plus the assigned producer, owned addresses,
 * contact directory, and tag assignments.
 *
 * @param clientId Primary key of the target client.
 * @returns Full client detail.
 *
 * @controller BrokerDeskCrmClientController.at
 * @path GET /clients/:clientId
 * @accessor api.functional.clients.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(clientId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}

/**
 * Create a new client.
 *
 * Accepts individual or business clients, optional initial tags, and an
 * initial contact directory for business clients. The owning organization
 * and assigned producer are resolved from the acting JWT identity unless an
 * authorized producer override applies.
 *
 * @param body Client creation payload.
 * @returns The newly created client in full detail.
 *
 * @controller BrokerDeskCrmClientController.create
 * @path POST /clients
 * @accessor api.functional.clients.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskClient.ICreate>;
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "POST",
    path: "/clients",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/clients";
}

/**
 * Update an existing client.
 *
 * Mutable business fields only; ownership and organization scoping never
 * change here.
 *
 * @param clientId Primary key of the target client.
 * @param body Fields to update, all optional.
 * @returns The updated client in full detail.
 *
 * @controller BrokerDeskCrmClientController.update
 * @path PUT /clients/:clientId
 * @accessor api.functional.clients.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(clientId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskClient.IUpdate>;
  export type Output = Primitive<IBrokerDeskClient>;

  export const METADATA = {
    method: "PUT",
    path: "/clients/:clientId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}

/**
 * Soft-delete a client.
 *
 * Retains the row for historical attribution while hiding the client from
 * active listings and blocking further business operations.
 *
 * @param clientId Primary key of the target client.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmClientController.erase
 * @path DELETE /clients/:clientId
 * @accessor api.functional.clients.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(clientId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/clients/:clientId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}`;
}

/**
 * Retrieve the chronological timeline of a client.
 *
 * Mixes activities, tasks, quotes, and policies into one chronology ordered
 * by their occurrence timestamps, serving as the relationship's shared
 * institutional memory.
 *
 * @param clientId Primary key of the target client.
 * @returns The client summary and its chronological entries.
 *
 * @controller BrokerDeskCrmClientController.timeline
 * @path GET /clients/:clientId/timeline
 * @accessor api.functional.clients.timeline
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function timeline(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<timeline.Output> {
  return PlainFetcher.fetch(connection, {
    ...timeline.METADATA,
    template: timeline.METADATA.path,
    path: timeline.path(clientId),
  });
}
export namespace timeline {
  export type Output = Primitive<IBrokerDeskClient.ITimeline>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/timeline",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/timeline`;
}
