/**
 * @packageDocumentation
 * @module api.functional.clients.addresses
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskAddress } from "../../../../../src/api/structures/BrokerDeskCrmAddress";

/**
 * List addresses owned by a client.
 *
 * @param clientId Primary key of the parent client.
 * @returns The client's owned addresses.
 *
 * @controller BrokerDeskCrmClientAddressController.index
 * @path GET /clients/:clientId/addresses
 * @accessor api.functional.clients.addresses.index
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function index(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
): Promise<index.Output> {
  return PlainFetcher.fetch(connection, {
    ...index.METADATA,
    template: index.METADATA.path,
    path: index.path(clientId),
  });
}
export namespace index {
  export type Output = Primitive<Array<IBrokerDeskAddress>>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/addresses",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/addresses`;
}

/**
 * Read one address owned by a client.
 *
 * @param clientId Primary key of the parent client.
 * @param addressId Primary key of the address.
 * @returns The address detail.
 *
 * @controller BrokerDeskCrmClientAddressController.at
 * @path GET /clients/:clientId/addresses/:addressId
 * @accessor api.functional.clients.addresses.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  addressId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(clientId, addressId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskAddress>;

  export const METADATA = {
    method: "GET",
    path: "/clients/:clientId/addresses/:addressId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    addressId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/addresses/${encodeURIComponent(addressId?.toString() ?? "null")}`;
}

/**
 * Attach a new typed address to a client.
 *
 * Risk addresses feed coverage eligibility and province-aware taxation;
 * mailing and billing addresses support correspondence and invoicing.
 *
 * @param clientId Primary key of the parent client.
 * @param body Address creation payload.
 * @returns The created address with ownership binding.
 *
 * @controller BrokerDeskCrmClientAddressController.create
 * @path POST /clients/:clientId/addresses
 * @accessor api.functional.clients.addresses.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(clientId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskAddress.ICreate>;
  export type Output = Primitive<IBrokerDeskAddress>;

  export const METADATA = {
    method: "POST",
    path: "/clients/:clientId/addresses",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (clientId: string & tags.Format<"uuid">) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/addresses`;
}

/**
 * Update an address owned by a client.
 *
 * @param clientId Primary key of the parent client.
 * @param addressId Primary key of the address.
 * @param body Fields to update, all optional.
 * @returns The updated address.
 *
 * @controller BrokerDeskCrmClientAddressController.update
 * @path PUT /clients/:clientId/addresses/:addressId
 * @accessor api.functional.clients.addresses.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  addressId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(clientId, addressId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskAddress.IUpdate>;
  export type Output = Primitive<IBrokerDeskAddress>;

  export const METADATA = {
    method: "PUT",
    path: "/clients/:clientId/addresses/:addressId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    addressId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/addresses/${encodeURIComponent(addressId?.toString() ?? "null")}`;
}

/**
 * Detach an address from a client, removing the ownership binding and
 * soft-deleting the address row.
 *
 * @param clientId Primary key of the parent client.
 * @param addressId Primary key of the address.
 * @returns Nothing.
 *
 * @controller BrokerDeskCrmClientAddressController.erase
 * @path DELETE /clients/:clientId/addresses/:addressId
 * @accessor api.functional.clients.addresses.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  clientId: string & tags.Format<"uuid">,
  addressId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(clientId, addressId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/clients/:clientId/addresses/:addressId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    clientId: string & tags.Format<"uuid">,
    addressId: string & tags.Format<"uuid">,
  ) =>
    `/clients/${encodeURIComponent(clientId?.toString() ?? "null")}/addresses/${encodeURIComponent(addressId?.toString() ?? "null")}`;
}
