/**
 * @packageDocumentation
 * @module api.functional.quotes.lines
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskQuoteLine } from "../../../../../src/api/structures/BrokerDeskQuoting";

/**
 * Attach a comparative product-option line to a quotation.
 *
 * Validates product eligibility against the parent quote's client
 * province, type, and language before attaching; carrier name and
 * code snapshots are frozen from the product's carrier.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param body Line creation payload.
 * @returns The created quote line.
 *
 * @controller BrokerDeskQuotingQuoteLineController.create
 * @path POST /quotes/:quoteId/lines
 * @accessor api.functional.quotes.lines.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  body: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(quoteId),
    },
    body,
  );
}
export namespace create {
  export type Body = Primitive<IBrokerDeskQuoteLine.ICreate>;
  export type Output = Primitive<IBrokerDeskQuoteLine>;

  export const METADATA = {
    method: "POST",
    path: "/quotes/:quoteId/lines",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (quoteId: string & tags.Format<"uuid">) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/lines`;
}

/**
 * Fetch one comparative line of a quotation in full detail.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param lineId Identifier of the target quote line.
 * @returns The quote line record.
 *
 * @controller BrokerDeskQuotingQuoteLineController.at
 * @path GET /quotes/:quoteId/lines/:lineId
 * @accessor api.functional.quotes.lines.at
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function at(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  lineId: string & tags.Format<"uuid">,
): Promise<at.Output> {
  return PlainFetcher.fetch(connection, {
    ...at.METADATA,
    template: at.METADATA.path,
    path: at.path(quoteId, lineId),
  });
}
export namespace at {
  export type Output = Primitive<IBrokerDeskQuoteLine>;

  export const METADATA = {
    method: "GET",
    path: "/quotes/:quoteId/lines/:lineId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    lineId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/lines/${encodeURIComponent(lineId?.toString() ?? "null")}`;
}

/**
 * Update a comparative line's coverage selections, rating inputs, or
 * priced amounts, or toggle its accepted flag.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param lineId Identifier of the target quote line.
 * @param body Fields to update, all optional.
 * @returns The updated quote line.
 *
 * @controller BrokerDeskQuotingQuoteLineController.update
 * @path PUT /quotes/:quoteId/lines/:lineId
 * @accessor api.functional.quotes.lines.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  lineId: string & tags.Format<"uuid">,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(quoteId, lineId),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskQuoteLine.IUpdate>;
  export type Output = Primitive<IBrokerDeskQuoteLine>;

  export const METADATA = {
    method: "PUT",
    path: "/quotes/:quoteId/lines/:lineId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    lineId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/lines/${encodeURIComponent(lineId?.toString() ?? "null")}`;
}

/**
 * Remove a comparative line from its quotation.
 *
 * @param quoteId Identifier of the owning quotation.
 * @param lineId Identifier of the target quote line.
 *
 * @controller BrokerDeskQuotingQuoteLineController.erase
 * @path DELETE /quotes/:quoteId/lines/:lineId
 * @accessor api.functional.quotes.lines.erase
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function erase(
  connection: IConnection,
  quoteId: string & tags.Format<"uuid">,
  lineId: string & tags.Format<"uuid">,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...erase.METADATA,
    template: erase.METADATA.path,
    path: erase.path(quoteId, lineId),
  });
}
export namespace erase {
  export const METADATA = {
    method: "DELETE",
    path: "/quotes/:quoteId/lines/:lineId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    quoteId: string & tags.Format<"uuid">,
    lineId: string & tags.Format<"uuid">,
  ) =>
    `/quotes/${encodeURIComponent(quoteId?.toString() ?? "null")}/lines/${encodeURIComponent(lineId?.toString() ?? "null")}`;
}
