/**
 * @packageDocumentation
 * @module api.functional.policies.coverages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive, tags } from "typia";

import type { IBrokerDeskPolicyCoverage } from "../../../../../src/api/structures/BrokerDeskPolicy";
import type { IPage } from "../../../../../src/api/structures/IPage";

/**
 * List active coverage schedule lines of a policy.
 *
 * @param policyId Owning policy id.
 * @returns Paginated coverage summaries.
 *
 * @controller BrokerDeskPolicySubsidiaryController.indexCoverages
 * @path GET /policies/:policyId/coverages
 * @accessor api.functional.policies.coverages.indexCoverages
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function indexCoverages(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
): Promise<indexCoverages.Output> {
  return PlainFetcher.fetch(connection, {
    ...indexCoverages.METADATA,
    template: indexCoverages.METADATA.path,
    path: indexCoverages.path(policyId),
  });
}
export namespace indexCoverages {
  export type Output = Primitive<IPage<IBrokerDeskPolicyCoverage.ISummary>>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/coverages",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (policyId: string & tags.Format<"uuid">) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/coverages`;
}

/**
 * Retrieve a single coverage schedule line.
 *
 * @param policyId Owning policy id.
 * @param coverageId Target coverage id.
 * @returns The coverage line.
 *
 * @controller BrokerDeskPolicySubsidiaryController.atCoverage
 * @path GET /policies/:policyId/coverages/:coverageId
 * @accessor api.functional.policies.coverages.atCoverage
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function atCoverage(
  connection: IConnection,
  policyId: string & tags.Format<"uuid">,
  coverageId: string & tags.Format<"uuid">,
): Promise<atCoverage.Output> {
  return PlainFetcher.fetch(connection, {
    ...atCoverage.METADATA,
    template: atCoverage.METADATA.path,
    path: atCoverage.path(policyId, coverageId),
  });
}
export namespace atCoverage {
  export type Output = Primitive<IBrokerDeskPolicyCoverage>;

  export const METADATA = {
    method: "GET",
    path: "/policies/:policyId/coverages/:coverageId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (
    policyId: string & tags.Format<"uuid">,
    coverageId: string & tags.Format<"uuid">,
  ) =>
    `/policies/${encodeURIComponent(policyId?.toString() ?? "null")}/coverages/${encodeURIComponent(coverageId?.toString() ?? "null")}`;
}
