/**
 * @packageDocumentation
 * @module api.functional.producers.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { Primitive } from "typia";

import type { IBrokerDeskProducer } from "../../../../../src/api/structures/BrokerDeskActorsProducer";

export * as sessions from "./sessions/index";
export * as licences from "./licences/index";

/**
 * Retrieve the profile of the authenticated producer.
 *
 * @returns The producer record of the caller, with licences and sessions.
 *
 * @controller BrokerDeskActorsProducerMeController.me
 * @path GET /producers/me
 * @accessor api.functional.producers.me.me
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function me(connection: IConnection): Promise<me.Output> {
  return PlainFetcher.fetch(connection, {
    ...me.METADATA,
    template: me.METADATA.path,
    path: me.path(),
  });
}
export namespace me {
  export type Output = Primitive<IBrokerDeskProducer>;

  export const METADATA = {
    method: "GET",
    path: "/producers/me",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/producers/me";
}

/**
 * Update the profile of the authenticated producer.
 *
 * @param body Mutable profile fields.
 * @returns The refreshed producer record.
 *
 * @controller BrokerDeskActorsProducerMeController.update
 * @path PUT /producers/me
 * @accessor api.functional.producers.me.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  body: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(),
    },
    body,
  );
}
export namespace update {
  export type Body = Primitive<IBrokerDeskProducer.IUpdate>;
  export type Output = Primitive<IBrokerDeskProducer>;

  export const METADATA = {
    method: "PUT",
    path: "/producers/me",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/producers/me";
}
